table Calendar
	lineageTag: 125a55a7-f38d-48af-9576-3434a2be4778
	dataCategory: Time

	column dim_date_key
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 6695e402-084a-4b41-ae77-d2e216d55d7d
		summarizeBy: none
		sourceColumn: dim_date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Date'
		dataType: dateTime
		isHidden
		isKey
		formatString: Short Date
		displayFolder: Hidden
		lineageTag: 586be44e-7cac-44c0-9408-96b8862cec23
		summarizeBy: none
		sourceColumn: Calendar Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: cb47a8a8-a434-4856-8050-b46c9f32b49d
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 29f8713d-fee5-4a33-ab7e-153671f89db2
		summarizeBy: none
		sourceColumn: quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: a1695e9b-19cb-44fd-b889-e074aa186d31
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_sort_number

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Week Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 2e589bd4-301f-4fd8-968a-c124601fc511
		summarizeBy: none
		sourceColumn: Week Number

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column fiscal_year_quarter
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 7a172323-ac6a-419e-9b11-019f5e4db866
		summarizeBy: none
		sourceColumn: fiscal_year_quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year_month_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 1f43ccb6-0273-48fe-aeb1-57df3ccb8d32
		summarizeBy: none
		sourceColumn: year_month_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscal_year_month_week
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 7eccb8ef-aa98-4af8-acf5-b3d1f62f2910
		summarizeBy: none
		sourceColumn: fiscal_year_month_week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Ending Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: Hidden
		lineageTag: 54e3e70e-3312-4607-b493-3bdee22eafc7
		summarizeBy: none
		sourceColumn: Fiscal Quarter Ending Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Month Ending Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: Hidden
		lineageTag: 9430ff33-2593-4fb3-9b8f-ffc9aa7f2705
		summarizeBy: none
		sourceColumn: Fiscal Month Ending Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Week Ending Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: Hidden
		lineageTag: a1a9a8a8-6113-4be1-95b1-16da2e785e11
		summarizeBy: none
		sourceColumn: Fiscal Week Ending Date
		sortByColumn: 'fiscal_year_month_week DESC'

		changedProperty = DataType

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column quarter_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 01cf897f-f44e-4f39-b6e9-ae15f42dcffc
		summarizeBy: none
		sourceColumn: quarter_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_sort_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 6b5fb9ce-323e-478d-bf0f-c79357217cb3
		summarizeBy: none
		sourceColumn: month_sort_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week'
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 83c1576b-3dfd-4fbd-9a2b-308acca7feea
		summarizeBy: none
		sourceColumn: Fiscal Week
		sortByColumn: 'Week Number'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sequential Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 7462331e-2f75-4d17-bdd5-e90bf061c74c
		summarizeBy: none
		sourceColumn: Sequential Quarter Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sequential Month Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: d5ecd6c6-5852-43d4-86fe-7974da9aeb01
		summarizeBy: none
		sourceColumn: Sequential Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sequential Week Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 2a55e5ed-b814-46d8-95d2-87ef2275a2c2
		summarizeBy: none
		sourceColumn: Sequential Week Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sequential_day_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: eb21a38f-7930-487f-abf5-cf0165839109
		summarizeBy: none
		sourceColumn: sequential_day_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week in Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: e7894bc0-16f0-4337-9925-a3abcd8f66a6
		summarizeBy: none
		sourceColumn: Fiscal Week in Quarter Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week in Month Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: f97f1177-b517-4fdb-8757-8d0129cd4ed4
		summarizeBy: none
		sourceColumn: Fiscal Week in Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Wave
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: f487d341-492d-4a57-ad1a-9fe3345c40fb
		summarizeBy: none
		sourceColumn: Wave

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Year Wave'
		dataType: string
		lineageTag: 8c7d59df-c79a-47a9-8ccd-bb6a0d5b4eeb
		summarizeBy: none
		sourceColumn: Year Wave

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Prior Wave'
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 16a86385-ca1a-4a4e-b041-90f9f875b2a1
		summarizeBy: none
		sourceColumn: Prior Wave

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Prior Year Wave'
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 0921d511-6106-469a-aa2b-437118b984a8
		summarizeBy: none
		sourceColumn: Prior Year Wave

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Wave Ending Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: Hidden
		lineageTag: a3583fe1-0e28-4239-b391-a1d499cba707
		summarizeBy: none
		sourceColumn: Wave Ending Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column R13W_LCM_CY
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 2d99c56d-c54e-423d-a223-70268cde4b57
		summarizeBy: none
		sourceColumn: R13W_LCM_CY

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column R13W_LCM_PY
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: acf3b730-4352-4f15-bc8c-9ad7eafb73c5
		summarizeBy: none
		sourceColumn: R13W_LCM_PY

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column year_wave_sort
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: bf8b745e-4a59-4a1c-8311-d10f2c5b3dd8
		summarizeBy: none
		sourceColumn: year_wave_sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ymdid
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: b41cf885-bc95-43a2-9253-8c54b2001dc6
		summarizeBy: none
		sourceColumn: ymdid

		annotation SummarizationSetBy = Automatic

	column rms_nielsen_week_ending_date
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 99cf7595-7870-4537-bf29-bd851f01a10a
		summarizeBy: none
		sourceColumn: rms_nielsen_week_ending_date

		annotation SummarizationSetBy = Automatic

	column ko_holiday
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 372b4ae5-7535-4f94-9b56-cc57f91dd11a
		summarizeBy: none
		sourceColumn: ko_holiday

		annotation SummarizationSetBy = Automatic

	column ko_pryr1_year_month_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: d43c1eca-fcb6-4490-bd26-a0ae7c88900f
		summarizeBy: none
		sourceColumn: ko_pryr1_year_month_number

		annotation SummarizationSetBy = Automatic

	column ko_pryr1_year_month_week_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: ee48fa19-2107-4489-a8eb-21cfb95ceafb
		summarizeBy: none
		sourceColumn: ko_pryr1_year_month_week_number

		annotation SummarizationSetBy = Automatic

	column ko_R12M
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 40b3757a-feb1-4dea-8060-00ea832d289e
		summarizeBy: none
		sourceColumn: ko_R12M

		annotation SummarizationSetBy = Automatic

	column ko_R24M_LCM_CY
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: ed2b4459-3c2e-473d-a86a-a2a05a3a9f2b
		summarizeBy: none
		sourceColumn: ko_R24M_LCM_CY

		annotation SummarizationSetBy = Automatic

	column ko_R24M_LCM_PY
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: eb47848a-bfd8-424a-8118-9b70ebf59608
		summarizeBy: none
		sourceColumn: ko_R24M_LCM_PY

		annotation SummarizationSetBy = Automatic

	column rms_period_key
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 18601e8e-512a-4438-a0d7-5c9fc0506597
		summarizeBy: none
		sourceColumn: rms_period_key

		annotation SummarizationSetBy = Automatic

	column rms_period_description
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 29e62537-f987-411d-ae46-07631b6ddaaf
		summarizeBy: none
		sourceColumn: rms_period_description

		annotation SummarizationSetBy = Automatic

	column 'fiscal_year_month_week DESC'
		dataType: double
		isHidden
		displayFolder: Hidden
		lineageTag: 61f6c3db-07cf-4357-9230-104ab1460eed
		summarizeBy: none
		sourceColumn: fiscal_year_month_week DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	hierarchy 'Fiscal Hierarchy'
		isHidden
		displayFolder: Hidden
		lineageTag: 8759cfc1-c73e-436b-b27f-48e187e1a76c

		level Year
			lineageTag: 209b0c7a-7128-4dcc-b807-ee6e16eac8f6
			column: Year

		level 'Fiscal Quarter'
			lineageTag: 4b60f78e-1091-413f-9873-f3e00cc7c958
			column: quarter

		level 'Fiscal Month'
			lineageTag: 05b678ee-f555-465c-a66c-c0dc553845ef
			column: month

		level 'Fiscal Week'
			lineageTag: 930ce919-0e2f-4735-b090-d39f2b7444f4
			column: 'Fiscal Week'

		changedProperty = IsHidden

	hierarchy 'Year Hierarchy'
		lineageTag: 05eeda6f-bfbe-45cd-8100-01c61df88c22

		level Year
			lineageTag: 766d7ffe-42e9-4fb5-848b-c92370150a64
			column: Year

		level Wave
			lineageTag: 5df32f63-d2a6-4b07-b525-a5d71c395325
			column: Wave

	partition Calendar = m
		mode: import
		source = ```
				let
				    Source = Sql.Database(Server, Database),
				    invoice_mdl_vw_Dim_Calendar = Source{[Schema="dbov3",Item="vw_Dim_Calendar"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(invoice_mdl_vw_Dim_Calendar,{{"fiscal_month_ending_date", "Fiscal Month Ending Date"}, {"fiscal_week_ending_date", "Fiscal Week Ending Date"}, {"date", "Calendar Date"}, 
				    {"fiscal_year", "year"}, {"fiscal_quarter", "quarter"}, {"fiscal_month", "month"}, {"month_number", "month_sort_number"}, {"fiscal_year_month", "year_month_number"}, {"week_number", "Week Number"}, 
				    {"ko_R13W_LCM_CY", "R13W_LCM_CY"}, {"ko_R13W_LCM_PY", "R13W_LCM_PY"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Calendar Date", type date}, {"Fiscal Month Ending Date", type date}, {"fiscal_quarter_ending_date", type date}, {"sovi_wave_ending_date", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each Date.Year([Calendar Date]) >= Date.Year(DateTime.LocalNow()) -3 and [Calendar Date] <= Date.From(DateTime.LocalNow())),
				    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows",{{"fiscal_quarter_ending_date", "Fiscal Quarter Ending Date"}, {"year", "Fiscal Year"}, {"sequential_quarter_number", "Sequential Quarter Number"}, {"sequential_month_number", "Sequential Month Number"}, {"sequential_week_number", "Sequential Week Number"}, {"fiscal_week_in_quarter_number", "Fiscal Week in Quarter Number"}, {"fiscal_week_in_month_number", "Fiscal Week in Month Number"}, {"sovi_wave", "Wave"}, {"sovi_wave_year", "Year Wave"}, {"sovi_prior_wave", "Prior Wave"}, {"sovi_wave_prior_year", "Prior Year Wave"}, {"sovi_wave_ending_date", "Wave Ending Date"}, {"Week Number", "Fiscal Week"}, {"fiscal_week", "Week Number"}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Renamed Columns1", "fiscal_year_month_week DESC", each [fiscal_year_month_week] * -1, type number),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Multiplication",{{"Fiscal Year", "Year"}})
				in
				    #"Renamed Columns2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

