{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Product\",\"Calendar\",\"Bottler\",\"Share of Market (Bottler)\",\"Database\",\"Server\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.7322.2 (Main)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"WebModelingEdit\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Database",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DnAIQDb_PreProd\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "949a451c-bf4b-45d6-bfeb-6bc1520614b8"
      },
      {
        "name": "Server",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syn-tccc-udp-dnao-us2-prd-01-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "68a04365-c9be-4626-a34b-39bf21107640"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_9f6873f3-399b-4043-8658-a3d1ea873877",
        "fromColumn": "Date Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Date Key",
        "toTable": "Calendar"
      },
      {
        "name": "AutoDetected_14173aa4-60e2-40a8-bdc9-a1d2a07b3e6d",
        "fromColumn": "Bottler Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Bottler Key",
        "toTable": "Bottler"
      },
      {
        "name": "393d3cc3-ff27-4392-87be-ca8d1993f802",
        "fromColumn": "Product Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Product Key",
        "toTable": "Product"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_fa6fa55e-cfc8-4cd3-981a-f4446ef96579",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "580d3510-b910-4232-8048-e315cb4f4f3f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "35460895-65a5-4c57-b62c-d80c43e3c8f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e08013e1-0fa5-44c4-ad19-4881674b889a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3a23ea5c-48fb-493f-ab2f-ff47e60526d9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2d7c8e84-c19a-44bc-8a46-bf6bc22d1ea6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4932da3e-d265-4dea-b1fa-a2d588aba6dd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7d3e200c-1cf5-4b4b-bc44-ee4afcf5f691",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ba65617e-3060-4875-b21f-ebed1b96fcad",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3072447f-1080-4058-bbb4-c5d5153b9ef6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "48183530-c034-4ef4-8b3f-07faedb03c2d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "78bce811-ea20-4e6c-b84a-a6d3270b6cba",
                "ordinal": 3
              }
            ],
            "lineageTag": "a050071a-8e86-4a6d-86be-c683565e952c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f4e615e7-9c67-48d8-92e6-06e9ebd53e19",
        "partitions": [
          {
            "name": "DateTableTemplate_fa6fa55e-cfc8-4cd3-981a-f4446ef96579",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Route-to-Market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_route_to_market",
            "lineageTag": "f765ce51-3640-49ad-b52c-504257f1e328",
            "sourceColumn": "Route-to-Market",
            "summarizeBy": "none"
          },
          {
            "name": "Total Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_total_category",
            "lineageTag": "730c3e2a-837d-4111-b1a9-a87d38a10c98",
            "sourceColumn": "Total Category",
            "summarizeBy": "none"
          },
          {
            "name": "ELT Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_elt_category",
            "lineageTag": "5c5831d5-538b-4e51-b126-f693d7ff9fc4",
            "sourceColumn": "ELT Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ce09b65e-7ad1-4944-8c76-1ed4b9479e18",
            "sourceColumn": "Product Key",
            "summarizeBy": "none"
          },
          {
            "name": "System Brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "92eb2537-03fe-4129-a002-7ef18009e54c",
            "sourceColumn": "System Brands",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "449554c5-ab47-437c-bccf-13f8ef84c7a2",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Flavor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01c41fb3-b3ec-4ad0-b675-b28ce03442f0",
            "sourceColumn": "Flavor",
            "summarizeBy": "none"
          },
          {
            "name": "Trademark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4c00b9e6-47fa-4112-82aa-0856c3c9d800",
            "sourceColumn": "Trademark",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1bf5f62b-2ed7-4292-962f-f9e8fa8a4ee1",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Consumption Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "812c4ab7-5f3f-45ce-8dd3-5f283c36b172",
            "sourceColumn": "Consumption Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sparkling vs. Non-Sparkling",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a1ee4b9-2047-4fff-9d64-be26da78c18f",
            "sourceColumn": "Sparkling vs. Non-Sparkling",
            "summarizeBy": "none"
          },
          {
            "name": "Beverage Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cf5be1a-451e-45ca-aa27-5997793c343d",
            "sourceColumn": "Beverage Type",
            "summarizeBy": "none"
          },
          {
            "name": "Container",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e7cb5f7-9ae2-498e-aaa6-a374f48a505f",
            "sourceColumn": "Container",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5504668-a103-4136-a290-708c061a4426",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "CBR Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ffe095c-e912-4e5e-a1d4-a9aa054f2023",
            "sourceColumn": "CBR Category",
            "summarizeBy": "none"
          },
          {
            "name": "ko_business_review_category_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebb878df-0120-4584-ae3d-58bb44710c58",
            "sourceColumn": "ko_business_review_category_id",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_Dim_Category",
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "System Brands",
                "column": "System Brands",
                "lineageTag": "b8180422-ed31-4c4a-bb24-c2b1943cfe01",
                "ordinal": 0
              },
              {
                "name": "Manufacturer",
                "column": "Manufacturer",
                "lineageTag": "0eb62445-e31c-46d6-8d6a-42d6541d3af7",
                "ordinal": 1
              },
              {
                "name": "Trademark",
                "column": "Trademark",
                "lineageTag": "9e5a1986-288f-47b6-91f1-40f28fb267c4",
                "ordinal": 2
              },
              {
                "name": "Brand",
                "column": "Brand",
                "lineageTag": "0d860c62-d03c-4f10-9422-63ccb7f607f8",
                "ordinal": 3
              }
            ],
            "lineageTag": "a4346caf-05df-4700-933a-ee6f40c86203"
          }
        ],
        "lineageTag": "eca76a9c-6f40-43d2-a69e-bc43b35111b7",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_dim_product = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_product\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(rms_mdl_vw_dim_product,{\"manufacturer_hier_id\", \"ko_system_brands_id\", \"ko_key_manufacturer_id\", \"ko_key_flavor_id\", \"ko_key_trademark_id\", \"ko_key_brand_id\", \"category_hier_id\", \"ko_route_to_market_id\", \"ko_ccna_selected_beverage_category\", \"ko_ccna_selected_beverage_category_id\", \"ko_total_category_id\", \"ko_elt_category_id\", \"package_hier_id\", \"ko_consumption_id\", \"ko_sparkling_non_sparkling_id\", \"ko_beverage_type_id\", \"ko_container_id\", \"ko_key_package_id\", \"updatedtimestamp\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"product_key\", \"Product Key\"}, {\"ko_system_brands\", \"System Brands\"}, {\"ko_key_manufacturer\", \"Manufacturer\"}, {\"ko_key_flavor\", \"Flavor\"}, {\"ko_key_trademark\", \"Trademark\"}, {\"ko_key_brand\", \"Brand\"}, {\"ko_route_to_market\", \"Route-to-Market\"}, {\"ko_total_category\", \"Total Category\"}, {\"ko_elt_category\", \"ELT Category\"}, {\"ko_consumption\", \"Consumption Type\"}, {\"ko_sparkling_non_sparkling\", \"Sparkling vs. Non-Sparkling\"}, {\"ko_beverage_type\", \"Beverage Type\"}, {\"ko_container\", \"Container\"}, {\"ko_key_package\", \"Package\"}}),",
                "  #\"Renamed Columns 1\" = Table.RenameColumns(#\"Renamed Columns\", {{\"ko_business_review_category\", \"CBR Category\"}})",
                "in",
                "    #\"Renamed Columns 1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebe186b9-782d-4395-a7c7-e4e397d0d478",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "c729fe57-8a0c-4a00-b2db-d63867da7bea",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_year",
            "formatString": "0",
            "lineageTag": "0e57ac97-731b-41bd-8f4b-04b3ab92db4d",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_quarter",
            "isHidden": true,
            "lineageTag": "0b7d41a5-dbe5-4218-8fdd-ae2d225be39e",
            "sortByColumn": "Quarter Number",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_month",
            "isHidden": true,
            "lineageTag": "190fad6b-78be-4dda-9cb8-4811a71c4ac5",
            "sortByColumn": "Month Number",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_week",
            "isHidden": true,
            "lineageTag": "c402ed21-2066-45b6-92e3-6af7b643b5a7",
            "sortByColumn": "Week Number",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_quarter",
            "lineageTag": "ef330159-1373-4d36-a61e-5b2b836c9359",
            "sortByColumn": "Sequential Quarter Number",
            "sourceColumn": "Fiscal Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_month",
            "lineageTag": "404519bd-d639-4c80-8431-1998d403d382",
            "sortByColumn": "Sequential Month Number",
            "sourceColumn": "Fiscal Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_week",
            "lineageTag": "4e839fcd-c091-4893-a868-d8d697ec5a44",
            "sortByColumn": "Sequential Week Number",
            "sourceColumn": "Fiscal Year Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_quarter_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "5bd75638-6233-4a0c-96d8-5eece4e2b5e2",
            "sourceColumn": "Fiscal Quarter Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_month_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "7837fc5a-2143-4bae-bc08-c7ab96501a9a",
            "sourceColumn": "Fiscal Month Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_week_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "3c2b353b-8433-4f14-b77d-f7373ec75438",
            "sourceColumn": "Fiscal Week Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a15d9580-c371-4ebf-8020-655afa48b670",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c151a0eb-440a-4ef1-befe-b9a62caa9d87",
            "sourceColumn": "Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "week_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3f30187-a16a-439d-a687-e513c73ba0cc",
            "sourceColumn": "Week Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sequential Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5697b30-4a13-4f81-900b-fc316f9983a8",
            "sourceColumn": "Sequential Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sequential Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d653e652-3bc4-4f22-befd-aa48bd503d63",
            "sourceColumn": "Sequential Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sequential Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_week_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "216ac7e6-f6e2-4042-85ae-1c6f0577c8b9",
            "sourceColumn": "Sequential Week Number",
            "summarizeBy": "none"
          },
          {
            "name": "Sequential Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_day_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "052f0daf-51d9-49ba-8e37-d32516b99a2e",
            "sourceColumn": "Sequential Day Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week In Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_week_in_quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fed31204-4bc5-4875-ba15-5663cf122405",
            "sourceColumn": "Fiscal Week In Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week In Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_week_in_month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39a8fdeb-fa11-4054-8cd2-e2cb3e13fdf1",
            "sourceColumn": "Fiscal Week In Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Nielsen Week Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "nielsen_week_ending_date",
            "formatString": "Short Date",
            "lineageTag": "9ba9e29f-c373-46f7-97b0-11e2b2d1bd3f",
            "sourceColumn": "Nielsen Week Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave",
            "isHidden": true,
            "lineageTag": "a90f1c54-5d66-4941-9fa2-e2b20927bbbc",
            "sourceColumn": "SOVI Wave",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_year",
            "isHidden": true,
            "lineageTag": "c99a884b-11ef-478d-ae37-7d5453092e2e",
            "sourceColumn": "SOVI Wave Year",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_number",
            "isHidden": true,
            "lineageTag": "aad521df-3687-4ac4-980e-adfe98890b7c",
            "sourceColumn": "SOVI Wave Number",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Sequential Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_sequential_number",
            "isHidden": true,
            "lineageTag": "7e692abf-568d-416e-866c-5dfc284eda55",
            "sourceColumn": "SOVI Sequential Number",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_ending_date",
            "isHidden": true,
            "lineageTag": "bdca21be-bb60-4716-ad39-8c0e82bf4995",
            "sourceColumn": "SOVI Wave Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "current_fiscal_period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c84adbd-9a52-446d-bea1-45b089e943d0",
            "sourceColumn": "current_fiscal_period",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "description": "rms_mdl vw_Dim_Period",
        "hierarchies": [
          {
            "name": "Fiscal Hierarchy by Period Name",
            "levels": [
              {
                "name": "Fiscal Year",
                "column": "Fiscal Year",
                "lineageTag": "3fddd164-fa83-4313-a24f-331b4f66fefe",
                "ordinal": 0
              },
              {
                "name": "Fiscal Quarter",
                "column": "Fiscal Quarter",
                "lineageTag": "b3bd22f3-dbbf-425c-8183-7f12592a8968",
                "ordinal": 1
              },
              {
                "name": "Fiscal Month",
                "column": "Fiscal Month",
                "lineageTag": "c4b805eb-b462-4e5e-a773-05e281264b23",
                "ordinal": 2
              },
              {
                "name": "Fiscal Week",
                "column": "Fiscal Week",
                "lineageTag": "8db1157e-cf45-4393-83ac-1387abf02f8a",
                "ordinal": 3
              }
            ],
            "lineageTag": "6ba426c4-6cd3-41bf-8d71-72f6d4e28c27"
          },
          {
            "name": "Fiscal Hierarchy by Ending Date",
            "levels": [
              {
                "name": "Fiscal Quarter Ending Date",
                "column": "Fiscal Quarter Ending Date",
                "lineageTag": "64c29836-136e-42e4-b7c4-6134b79a94b1",
                "ordinal": 0
              },
              {
                "name": "Fiscal Month Ending Date",
                "column": "Fiscal Month Ending Date",
                "lineageTag": "faf97246-cf51-4bc8-8115-28387ab893dc",
                "ordinal": 1
              },
              {
                "name": "Fiscal Week Ending Date",
                "column": "Fiscal Week Ending Date",
                "lineageTag": "c9413ce1-f6e4-481d-83a9-51a7d5378ff7",
                "ordinal": 2
              }
            ],
            "lineageTag": "a85618a8-c6b5-42fe-995e-c362781503ce"
          }
        ],
        "lineageTag": "bf8ac801-920a-42f6-a059-686f7b0daaa1",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_Dim_Period = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_period\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(rms_mdl_vw_Dim_Period,{{\"date\", type date}, {\"fiscal_quarter_ending_date\", type date}, {\"fiscal_month_ending_date\", type date}, {\"fiscal_week_ending_date\", type date}, {\"nielsen_week_ending_date\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"fiscal_month\", \"Fiscal Month\"}, {\"fiscal_month_ending_date\", \"Fiscal Month Ending Date\"}, {\"fiscal_quarter\", \"Fiscal Quarter\"}, {\"fiscal_quarter_ending_date\", \"Fiscal Quarter Ending Date\"}, {\"fiscal_week\", \"Fiscal Week\"}, {\"fiscal_week_ending_date\", \"Fiscal Week Ending Date\"}, {\"fiscal_week_in_month_number\", \"Fiscal Week In Month Number\"}, {\"fiscal_week_in_quarter_number\", \"Fiscal Week In Quarter Number\"}, {\"fiscal_year\", \"Fiscal Year\"}, {\"fiscal_year_month\", \"Fiscal Year Month\"}, {\"fiscal_year_quarter\", \"Fiscal Year Quarter\"}, {\"fiscal_year_week\", \"Fiscal Year Week\"}, {\"month_number\", \"Month Number\"}, {\"nielsen_week_ending_date\", \"Nielsen Week Ending Date\"}, {\"quarter_number\", \"Quarter Number\"}, {\"sequential_day_number\", \"Sequential Day Number\"}, {\"sequential_month_number\", \"Sequential Month Number\"}, {\"sequential_quarter_number\", \"Sequential Quarter Number\"}, {\"sequential_week_number\", \"Sequential Week Number\"}, {\"sovi_sequential_number\", \"SOVI Sequential Number\"}, {\"sovi_wave\", \"SOVI Wave\"}, {\"sovi_wave_ending_date\", \"SOVI Wave Ending Date\"}, {\"sovi_wave_number\", \"SOVI Wave Number\"}, {\"sovi_wave_year\", \"SOVI Wave Year\"}, {\"week_number\", \"Week Number\"}, {\"date\", \"Date\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Fiscal Year\", Int64.Type}, {\"Quarter Number\", Int64.Type}, {\"Month Number\", Int64.Type}, {\"Week Number\", Int64.Type}, {\"Sequential Quarter Number\", Int64.Type}, {\"Sequential Month Number\", Int64.Type}, {\"Sequential Week Number\", Int64.Type}, {\"Sequential Day Number\", Int64.Type}, {\"Fiscal Week In Quarter Number\", Int64.Type}, {\"Fiscal Week In Month Number\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"updatedtimestamp\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"date_key\", \"Date Key\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Bottler",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Bottler Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1e4c3ff5-9739-473c-b5f0-bf30cb31fb6a",
            "sourceColumn": "Bottler Key",
            "summarizeBy": "none"
          },
          {
            "name": "Market Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bf66090c-fa6d-44b1-9d70-8236cb4d4934",
            "sourceColumn": "Market Description",
            "summarizeBy": "none"
          },
          {
            "name": "Bottler",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4c39f7ab-a2fd-4cca-aa76-350c749ecd40",
            "sourceColumn": "Bottler",
            "summarizeBy": "none"
          },
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca03680d-deb1-4628-90ac-fa67536782d3",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c7a203fe-9e66-40c6-b0ae-72fa6d5a151b",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_dim_bottlers",
        "hierarchies": [
          {
            "name": "Bottler Hierarchy",
            "levels": [
              {
                "name": "Bottler",
                "column": "Bottler",
                "lineageTag": "f15fa183-5506-46e3-8672-f212ca3841ea",
                "ordinal": 0
              },
              {
                "name": "Division",
                "column": "Division",
                "lineageTag": "96bbdad6-af6f-4d67-b191-793460c66b43",
                "ordinal": 1
              },
              {
                "name": "Market Description",
                "column": "Market Description",
                "lineageTag": "06ce6764-8bb3-4e48-809b-ff07d62222d8",
                "ordinal": 2
              }
            ],
            "lineageTag": "5b05bbbe-bd74-4779-9669-50cfe7b72ec9"
          }
        ],
        "lineageTag": "4d8d640d-7d58-481a-a444-344e4a21a8fa",
        "partitions": [
          {
            "name": "Bottler",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_dim_bottlers = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_bottlers\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_dim_bottlers,{{\"bottler\", \"Bottler\"}, {\"channel\", \"Channel\"}, {\"market_description\", \"Market Description\"}, {\"parent_market_description\", \"Parent Market Description\"}, {\"bottler_key\", \"Bottler Key\"}, {\"division\", \"Division",
                "\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"updatedtimestamp\", \"Parent Market Description\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Share of Market (Bottler)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Bottler Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f09f32e-e575-4ff8-8824-d79362d38d72",
            "sourceColumn": "Bottler Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d62b2cc7-1886-4824-b45d-ac738e53d5b2",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "dollars_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "Dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "cc488b7f-cf18-47f2-839b-615a94bd885f",
            "sourceColumn": "dollars_",
            "summarizeBy": "none"
          },
          {
            "name": "base_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "base_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "5ea7e42f-598a-465a-b39d-0a3c6454d71b",
            "sourceColumn": "base_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "incr_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "incr_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "0cccb44c-6bf3-48c5-83f3-e6f984336532",
            "sourceColumn": "incr_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "subsidized_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "subsidized_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "258febef-b48e-49d0-b6fe-7e48b68ca6d4",
            "sourceColumn": "subsidized_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "eq_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "ed31e619-1eae-490c-a8ed-2b93400b2e37",
            "sourceColumn": "eq_",
            "summarizeBy": "none"
          },
          {
            "name": "base_eq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "base_eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "652647b7-65e0-45c6-97b8-d1fe13f5eb61",
            "sourceColumn": "base_eq",
            "summarizeBy": "none"
          },
          {
            "name": "incr_eq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "incr_eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "ab10d9cd-6319-4498-98fe-66f35a624088",
            "sourceColumn": "incr_eq",
            "summarizeBy": "none"
          },
          {
            "name": "subsidized_eq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "subsidized_eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "737b950c-e138-4887-8da0-fa4622aab8ea",
            "sourceColumn": "subsidized_eq",
            "summarizeBy": "none"
          },
          {
            "name": "units_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "units",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "2607beb9-65d5-4493-a820-dfab5c166997",
            "sourceColumn": "units_",
            "summarizeBy": "none"
          },
          {
            "name": "any_promo_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "any_promo_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "cf4a8bcb-c34c-4436-b9b6-074031482694",
            "sourceColumn": "any_promo_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "no_promo_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "no_promo_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "4204df4a-5f64-464f-8400-ce4c169d54f6",
            "sourceColumn": "no_promo_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "any_display_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "any_display_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "203583da-fd82-4bbd-bd61-592b8142788f",
            "sourceColumn": "any_display_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "any_feature_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "any_feature_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "12a863c5-aca4-40d2-996c-595c4dd0f9ec",
            "sourceColumn": "any_feature_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "feat_and_display_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "feat_and_display_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "80755795-fa67-4b95-a074-2ff9a0533897",
            "sourceColumn": "feat_and_display_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "price_decr_only_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "price_decr_only_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "1233dd1c-831a-4d6c-8ce0-b5ebaedf5982",
            "sourceColumn": "price_decr_only_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "feature_without_display_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "feature_without_display_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "15d03d81-ba0e-401e-9eb3-f4b5a3b3a289",
            "sourceColumn": "feature_without_display_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "disp_without_feature_dollars",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "disp_without_feature_dollars",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "f189b3c8-cce2-47bc-ab77-f00c5073ac1e",
            "sourceColumn": "disp_without_feature_dollars",
            "summarizeBy": "none"
          },
          {
            "name": "any_promo_eq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "any_promo_eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "71e49d8e-e645-4666-a398-569da58a2f79",
            "sourceColumn": "any_promo_eq",
            "summarizeBy": "none"
          },
          {
            "name": "no_promo_eq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "description": "no_promo_eq",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "6ef0fd49-8f0e-497a-8e12-3e0e27f20c4d",
            "sourceColumn": "no_promo_eq",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "495dcefe-1684-4a87-8471-eaa430ff85b0",
            "sourceColumn": "Product Key",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_fact_bottlerweekly",
        "lineageTag": "35a8f58b-9d19-4831-9d4d-3aa9fd9ff2c3",
        "measures": [
          {
            "name": "Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[dollars_])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "96029d87-0d00-4e2e-82e2-7db0a856376b"
          },
          {
            "name": "Units",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[units_])",
            "formatString": "#,0.00",
            "lineageTag": "664145ce-fa7a-4422-bcea-c72cfc93ba67"
          },
          {
            "name": "Any Display Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[any_display_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a23e480e-d642-4312-9f54-63d3ca0d9372"
          },
          {
            "name": "Any Feature Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[any_feature_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "cd7b7d6a-cef2-49db-8c65-2771bdb28b6c"
          },
          {
            "name": "Any Promo Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[any_promo_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1740e181-04a1-43c0-ad3f-80de32fd881f"
          },
          {
            "name": "Any Promo EQ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[any_promo_eq])",
            "formatString": "#,0.00",
            "lineageTag": "35136dd1-091e-4f7f-95f3-3d6b1fce7d97"
          },
          {
            "name": "Base Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[base_dollars]) ",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "028caf8b-4283-479f-ae58-6d9fb75213cb"
          },
          {
            "name": "Base EQ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[base_eq])",
            "formatString": "#,0.00",
            "lineageTag": "e27aa51f-ee17-43c0-8b1e-739b98592524"
          },
          {
            "name": "Feature without Display Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[feature_without_display_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "54c13528-cb7c-4e53-a7eb-0d2815a96104"
          },
          {
            "name": "Incremental Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[incr_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a23e740a-9f5b-4f32-93ef-ae399fcd9b1a"
          },
          {
            "name": "Incremental EQ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[incr_eq])",
            "formatString": "#,0.00",
            "lineageTag": "0a6f48a4-0a77-42e1-8361-f1d3fc983726"
          },
          {
            "name": "No Promo Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM([no_promo_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "45aebcb1-4925-4ca6-b628-b521be743871"
          },
          {
            "name": "No Promo EQ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[no_promo_eq])",
            "formatString": "0.00",
            "lineageTag": "a2c15d34-656c-4622-a39c-a5060e17dd3a"
          },
          {
            "name": "Price Decrease Only Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[price_decr_only_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1ab9dd6e-37aa-48fd-99ad-622a7e1951d1"
          },
          {
            "name": "Subsidized Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[subsidized_dollars])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "ccb8fa09-b656-4375-8c38-5c4544fce584"
          },
          {
            "name": "Subsidized EQ",
            "displayFolder": "Base Measures",
            "expression": "sum('Share of Market (Bottler)'[subsidized_eq])",
            "formatString": "0.00",
            "lineageTag": "2487b034-6653-465b-9cb0-c07d48304704"
          },
          {
            "name": "EQs",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[eq_])",
            "formatString": "#,0.00",
            "lineageTag": "540bce0b-44ee-48ee-b6e6-d2579cdda833"
          },
          {
            "name": "Share of Dollars",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[Dollars]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Dollars],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Dollars],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    Results",
              "",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "71cd2588-a4e6-4c78-8db6-3cfe6942db7e"
          },
          {
            "name": "Share of Dollars YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "36ea8a30-e921-4b7b-a1bf-6392e488c26b"
          },
          {
            "name": "Share of Dollars YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "5501b3c3-49be-48e1-a921-5c1663addee3"
          },
          {
            "name": "Share of Dollars QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e70d4632-794f-4880-8294-da1f7d8b1a3e"
          },
          {
            "name": "Share of Dollars R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fa6ca625-403f-43fe-970a-be1b38ba880a"
          },
          {
            "name": "Share of Dollars LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "faf8b21e-f939-4ac2-b79f-15602c3a5b6a"
          },
          {
            "name": "Share of Dollars R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "b3cc5b17-1bdc-45a5-98a2-3d1ac1d57ae2"
          },
          {
            "name": "Share of Dollars LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "1be6e986-1a3b-4da7-8543-b74dd94ebfe5"
          },
          {
            "name": "Share of Dollars QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "19a8286b-17ea-4146-abb3-f7b6a5d12187"
          },
          {
            "name": "YoY Share of Dollars (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Dollars LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of Dollars MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of Dollars QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of Dollars YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "c8f48288-4c12-4770-8321-0f2465a733ff"
          },
          {
            "name": "Share of Dollars MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "40d6a11d-16a2-40fa-861e-dad21a1d94d5"
          },
          {
            "name": "Share of Dollars MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "96296023-e5d6-4154-b4c2-6c95b9bfeda0"
          },
          {
            "name": "Share of Dollars R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f1268a59-33ff-4e40-9cc0-0086f27a5b87"
          },
          {
            "name": "Share of Dollars R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "86e535d3-f37f-497b-8ef9-b59915ad12e7"
          },
          {
            "name": "Share of Dollars R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b5984d42-044e-4477-bf90-a7cfefd0f4f3"
          },
          {
            "name": "Share of Dollars R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "e771d338-4eab-4975-aa66-c7ec0df04fe1"
          },
          {
            "name": "Share of Units",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[Units]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Units],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Units],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    Results",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b32a3360-d3de-4725-becf-121abd3b41f3"
          },
          {
            "name": "Share of Units YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ef2f15be-e80b-4c66-a362-c06b8afa37a7"
          },
          {
            "name": "Share of Units YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "91050864-e1d6-4e5e-8804-8025f847973e"
          },
          {
            "name": "Share of Units QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "71694b9f-2bad-4ef3-add0-500fb34e683b"
          },
          {
            "name": "Share of Units R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a4a929fd-7999-44be-9139-42a370048785"
          },
          {
            "name": "Share of Units LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7911b93b-2363-4c92-ba2f-0867424194d4"
          },
          {
            "name": "Share of Units R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "7449e855-382e-4687-bdd5-8b1662e41753"
          },
          {
            "name": "Share of Units LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "921b9743-b814-49a9-9313-e245a2b56e41"
          },
          {
            "name": "Share of Units QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "364cb00b-4823-41ce-b666-2464f3427d78"
          },
          {
            "name": "YoY Share of Units (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Units LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of Units MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of Units QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of Units YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "6131113b-d0dd-46d9-99e4-310672ccba7c"
          },
          {
            "name": "Share of Units MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f0e60a2f-b001-4712-8a5e-0cd13689d890"
          },
          {
            "name": "Share of Units MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "aefc2a33-4775-4984-b925-2b5528e5334c"
          },
          {
            "name": "Share of Units R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "729237fc-9882-4535-8f16-f2d0f020975e"
          },
          {
            "name": "Share of Units R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "cc4fef0c-5dc6-43e4-a61f-0189c79b3b6e"
          },
          {
            "name": "Share of Units R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dbc88fcd-712f-4e94-aabd-890427942c7c"
          },
          {
            "name": "Share of Units R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "a1b578c0-f834-4611-ab9f-a204aae75e79"
          },
          {
            "name": "Share of EQs",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[EQs]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[EQs],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[EQs],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    Results",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2b5ddf63-49ae-4494-9d70-60c840567b4d"
          },
          {
            "name": "Share of EQs YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4d1fd9c4-d835-49d6-84f3-4488c881bf0c"
          },
          {
            "name": "Share of EQs YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "542f989d-9ebc-4a9d-bbcd-d97705f5961a"
          },
          {
            "name": "Share of EQs QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7c3c5eb8-87c8-4ff6-bf48-0a927a2698b2"
          },
          {
            "name": "Share of EQs R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "58598fff-1ef9-45f7-8362-a211d9ff14d3"
          },
          {
            "name": "Share of EQs LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "94ea4007-f1a9-4a44-954e-55954f172af2"
          },
          {
            "name": "Share of EQs R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "8efc6a03-e075-4700-b529-4c6a2e34504a"
          },
          {
            "name": "Share of EQs LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "81b4c259-8f95-4a64-a74c-faab9cd63ace"
          },
          {
            "name": "Share of EQs QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "bd799491-8a86-4127-add4-b0ba31f3003c"
          },
          {
            "name": "YoY Share of EQs (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of EQs LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of EQs MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of EQs QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of EQs YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "7e446a38-5baa-4416-ae40-36ca6cc60c0f"
          },
          {
            "name": "Share of EQs MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8d2ffda3-318b-4c6b-a61a-fa0b971743cf"
          },
          {
            "name": "Share of EQs MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "98b54be7-4df6-49d3-b18b-02bc37da6ac6"
          },
          {
            "name": "Share of EQs R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "de8168d4-b539-49ac-b391-e249f2dd7907"
          },
          {
            "name": "Share of EQs R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "9a609427-e659-4f41-9d3b-823f19e78e3f"
          },
          {
            "name": "Share of EQs R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b3ef1bd4-5bf0-4612-b8c1-20dacccf5167"
          },
          {
            "name": "Share of EQs R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "c4f6bec7-87c7-4c0a-9546-430019517aab"
          }
        ],
        "partitions": [
          {
            "name": "Share of Market (Bottler)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_fact_bottlerweekly = Source{[Schema=\"rms_mdl\",Item=\"vw_fact_bottlerweekly_ss\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_fact_bottlerweekly,{{\"bottler_key\", \"Bottler Key\"}, {\"date_key\", \"Date Key\"}, {\"product_key\", \"Product Key\"}, {\"dollars\", \"dollars_\"}, {\"eq\", \"eq_\"}, {\"units\", \"units_\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}