{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Share of Market (Customer)\",\"Share of Market (Bottler)\",\"Product\",\"Customer\",\"Bottler\",\"Calendar\",\"Database\",\"Server\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.7314.2 (Main)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"WebModelingEdit\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Database",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DnAIQDb_PreProd\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a355552d-9ccd-424a-9555-87c02c405aae"
      },
      {
        "name": "Server",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syn-tccc-udp-dnao-us2-prd-01-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f209b676-bc36-4b2e-b7a8-838ebe4c88fc"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_2ad11453-c73d-4e96-b07b-a232d24a5d15",
        "fromColumn": "Customer Key",
        "fromTable": "Share of Market (Customer)",
        "toColumn": "Customer Key",
        "toTable": "Customer"
      },
      {
        "name": "AutoDetected_575511dc-9722-4df7-8111-d51f14712cca",
        "fromColumn": "Date Key",
        "fromTable": "Share of Market (Customer)",
        "toColumn": "Date Key",
        "toTable": "Calendar"
      },
      {
        "name": "AutoDetected_5f1a4b96-fd80-49d3-a958-5acbdc74dfd9",
        "fromColumn": "Product Key",
        "fromTable": "Share of Market (Customer)",
        "toColumn": "Product Key",
        "toTable": "Product"
      },
      {
        "name": "AutoDetected_d668f344-a34f-4238-94a9-3c445912b7c1",
        "fromColumn": "Date Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Date Key",
        "toTable": "Calendar"
      },
      {
        "name": "AutoDetected_ad2d5dba-9269-49a6-816e-347f0ab42fb5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Product Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Product Key",
        "toTable": "Product"
      },
      {
        "name": "AutoDetected_aa979c03-eeac-4c3f-8e4c-4118d5149dda",
        "fromColumn": "Bottler Key",
        "fromTable": "Share of Market (Bottler)",
        "toColumn": "Bottler Key",
        "toTable": "Bottler"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_fa6fa55e-cfc8-4cd3-981a-f4446ef96579",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "580d3510-b910-4232-8048-e315cb4f4f3f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "35460895-65a5-4c57-b62c-d80c43e3c8f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e08013e1-0fa5-44c4-ad19-4881674b889a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3a23ea5c-48fb-493f-ab2f-ff47e60526d9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2d7c8e84-c19a-44bc-8a46-bf6bc22d1ea6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4932da3e-d265-4dea-b1fa-a2d588aba6dd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7d3e200c-1cf5-4b4b-bc44-ee4afcf5f691",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ba65617e-3060-4875-b21f-ebed1b96fcad",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3072447f-1080-4058-bbb4-c5d5153b9ef6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "48183530-c034-4ef4-8b3f-07faedb03c2d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "78bce811-ea20-4e6c-b84a-a6d3270b6cba",
                "ordinal": 3
              }
            ],
            "lineageTag": "a050071a-8e86-4a6d-86be-c683565e952c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f4e615e7-9c67-48d8-92e6-06e9ebd53e19",
        "partitions": [
          {
            "name": "DateTableTemplate_fa6fa55e-cfc8-4cd3-981a-f4446ef96579",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Share of Market (Customer)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5197f95b-144f-4289-a409-9ab650d29090",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "de2bb52c-8611-481a-9cb3-9bd4bd834199",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74bf2d48-e580-4d68-977f-2c5af40b903c",
            "sourceColumn": "Product Key",
            "summarizeBy": "none"
          },
          {
            "name": "dollars_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "7105d0fb-d427-46a0-9e70-96b7c41978c5",
            "sourceColumn": "dollars_",
            "summarizeBy": "none"
          },
          {
            "name": "eq_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "261a74fe-d8d9-4ffb-a986-4a25961d4d10",
            "sourceColumn": "eq_",
            "summarizeBy": "none"
          },
          {
            "name": "units_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "3f2b06ac-2064-4c42-ba1b-b4f5e7484a0f",
            "sourceColumn": "units_",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_fact_customerweekly",
        "lineageTag": "6cb82dd4-93c0-4059-bb90-aeb6258621f4",
        "measures": [
          {
            "name": "Dollars",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Customer)'[dollars_])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1382b58c-42ed-4851-869f-e9ea27ff92c5"
          },
          {
            "name": "Units",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Customer)'[units_])",
            "formatString": "#,0.00",
            "lineageTag": "72b63072-7797-4623-b70c-bf93ee7e7c0e"
          },
          {
            "name": "EQs",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Customer)'[eq_])",
            "formatString": "#,0.00",
            "lineageTag": "16ba4355-d334-4ec9-848b-5a87ac580849"
          },
          {
            "name": "Share of Dollars",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Customer)'[Dollars]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Dollars],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Dollars],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "85312950-f855-4079-896c-d6876490573c"
          },
          {
            "name": "Share of Dollars YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "80ac4a43-16db-44f4-b09e-58bc647fc82f"
          },
          {
            "name": "Share of Dollars YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "e6da986f-5945-421c-9cce-e30adeb41252"
          },
          {
            "name": "Share of Dollars QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f356f5db-252d-4ec1-9aab-0068e0202fe5"
          },
          {
            "name": "Share of Dollars R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d4f8943a-c2ff-4126-af37-126fccb18e2c"
          },
          {
            "name": "Share of Dollars LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f813fd44-fc51-49c4-8d72-65ce51fc9e0d"
          },
          {
            "name": "Share of Dollars R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "5968c73c-150b-40ea-8653-42edcf576624"
          },
          {
            "name": "Share of Dollars LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "b22cceab-689f-4612-b7b2-3e2c15751cdf"
          },
          {
            "name": "Share of Dollars QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "56abc858-589a-42db-91f5-9322b8e37d3f"
          },
          {
            "name": "YoY Share of Dollars (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Dollars LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Customer)'[Share of Dollars MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Customer)'[Share of Dollars QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Customer)'[Share of Dollars YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "2ad14b18-4988-4e1a-a7d3-1cc8d80e4c65"
          },
          {
            "name": "Share of Dollars MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b0cf051a-c6da-436f-a89a-b2c079758e88"
          },
          {
            "name": "Share of Dollars MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "bc3bf0af-a560-4355-9108-504d22aa9ce3"
          },
          {
            "name": "Share of Dollars R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "652812d8-d0dc-4b2f-9731-c28950ca58c5"
          },
          {
            "name": "Share of Dollars R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "d5e8b0eb-6ad9-4939-af46-18a93b670f12"
          },
          {
            "name": "Share of Dollars R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d3337644-e879-4f4e-b763-539ea9a7e784"
          },
          {
            "name": "Share of Dollars R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Dollars],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "6d45fb1d-2746-442f-93b8-88b3bf7987bd"
          },
          {
            "name": "Share of EQs",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Customer)'[EQs]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[EQs],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[EQs],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "985e4cba-9fc5-417f-900e-aa6661138f6f"
          },
          {
            "name": "Share of EQs YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2a070a00-ed31-4eef-b6aa-ce7490c381ac"
          },
          {
            "name": "Share of EQs YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "38607acd-0937-4b62-815f-80ec3984034d"
          },
          {
            "name": "Share of EQs QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f08e4024-ae2d-4969-b831-f54810fea8d7"
          },
          {
            "name": "Share of EQs R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b2b1d728-c52f-43f2-bc08-1dec7cdfdf0d"
          },
          {
            "name": "Share of EQs LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d5540c20-8158-4edc-89f9-afd7da759367"
          },
          {
            "name": "Share of EQs R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "c00fa80a-d9df-4e02-b3c5-b240d896edad"
          },
          {
            "name": "Share of EQs LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "82e3f05d-e869-41db-b4c8-db511453b49b"
          },
          {
            "name": "Share of EQs QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "1f1541f8-4aff-4967-9c29-b7a3c2b7df79"
          },
          {
            "name": "YoY Share of EQs (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of EQs LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Customer)'[Share of EQs MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Customer)'[Share of EQs QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Customer)'[Share of EQs YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "1ca899d9-8c2c-439b-852c-3e2d0db8ee6c"
          },
          {
            "name": "Share of EQs MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "04c1441b-2f81-45cb-9d84-a894fd856979"
          },
          {
            "name": "Share of EQs MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "9ec225ae-5851-4316-8957-9a1947041608"
          },
          {
            "name": "Share of EQs R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "26a85258-b5b5-4832-9597-fd27f947c457"
          },
          {
            "name": "Share of EQs R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of EQs R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "07a2477f-ddad-4962-aa7a-6301559a0403"
          },
          {
            "name": "Share of EQs R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8c0481c1-a041-46dd-a0f3-05ca5c52b04c"
          },
          {
            "name": "Share of EQs R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of EQs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "224211af-4be6-48d1-965d-5afa18a07c0f"
          },
          {
            "name": "Share of Units",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Customer)'[Units]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Units],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Units],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1cd784e2-efd5-4cc5-af5e-76f2afd0bff8"
          },
          {
            "name": "Share of Units YTD",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "226d3adc-c0ef-42e9-b00f-b36132d170c1"
          },
          {
            "name": "Share of Units YTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units YTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "5094037a-5ca4-4340-a8f5-c4fea0fce206"
          },
          {
            "name": "Share of Units QTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9f2e1ec9-5394-41f8-89e6-9793396f8393"
          },
          {
            "name": "Share of Units R4W",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "72febe24-7a89-4cb5-9576-89db90240516"
          },
          {
            "name": "Share of Units LW",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "6f9fe07c-f071-40a0-94ae-59979794fb82"
          },
          {
            "name": "Share of Units R4W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units R4W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "da5e86ed-cefe-4346-b9b4-76d9052f961f"
          },
          {
            "name": "Share of Units LW vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units LW]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "2f481d6d-9afc-48d0-8420-c0f8bc53f813"
          },
          {
            "name": "Share of Units QTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Dollars QTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "c1d4ced0-63b1-4711-9feb-04e4a568a759"
          },
          {
            "name": "YoY Share of Units (% pts)",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Units LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Customer)'[Share of Units MTD vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Customer)'[Share of Units QTD vs. PY (% pts)],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Customer)'[Share of Units YTD vs. PY (% pts)]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "23064eb8-7420-4e1e-97b1-46f5987e0895"
          },
          {
            "name": "Share of Units MTD",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b0d8d4b1-132f-4c74-8f65-645c02ce5927"
          },
          {
            "name": "Share of Units MTD vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units MTD]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "71b13144-e989-484f-a0bb-c9837498552c"
          },
          {
            "name": "Share of Units R13W",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cd5ca21a-3798-43d9-899f-958b139ff817"
          },
          {
            "name": "Share of Units R13W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units R13W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "455b0b08-6825-46c6-877d-e00cd804991f"
          },
          {
            "name": "Share of Units R52W",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "53698888-b16d-45d5-b336-6ffabf3f62f9"
          },
          {
            "name": "Share of Units R52W vs. PY (% pts)",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Customer)'[Share of Units],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Customer)'[Share of Units R52W]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "8592e3ee-e14d-4b34-acaf-dd80c78b0acf"
          }
        ],
        "partitions": [
          {
            "name": "Share of Market (Customer)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_fact_customerweekly = Source{[Schema=\"rms_mdl\",Item=\"vw_fact_customerweekly\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_fact_customerweekly,{{\"customer_key\", \"Customer Key\"}, {\"date_key\", \"Date Key\"}, {\"product_key\", \"Product Key\"}, {\"dollars\", \"dollars_\"}, {\"eq\", \"eq_\"}, {\"units\", \"units_\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Route-to-Market",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_route_to_market",
            "lineageTag": "f765ce51-3640-49ad-b52c-504257f1e328",
            "sourceColumn": "Route-to-Market",
            "summarizeBy": "none"
          },
          {
            "name": "Total Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_total_category",
            "lineageTag": "730c3e2a-837d-4111-b1a9-a87d38a10c98",
            "sourceColumn": "Total Category",
            "summarizeBy": "none"
          },
          {
            "name": "ELT Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "ko_elt_category",
            "lineageTag": "5c5831d5-538b-4e51-b126-f693d7ff9fc4",
            "sourceColumn": "ELT Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "acd06473-bf20-47be-a01e-e436b0551e23",
            "sourceColumn": "Product Key",
            "summarizeBy": "none"
          },
          {
            "name": "System Brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2e1986b7-68df-4b91-ab90-6c028f7d4f27",
            "sourceColumn": "System Brands",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7be48039-7d2f-47fb-82d4-2854a40e81c3",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "Flavor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e67bff78-01d3-4693-8fcb-a3a71192dc6c",
            "sourceColumn": "Flavor",
            "summarizeBy": "none"
          },
          {
            "name": "Trademark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5ec991a9-226f-4655-b9ce-54ed8473d488",
            "sourceColumn": "Trademark",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "335e5cdd-5a40-4913-a5c6-546424c183da",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Consumption Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6dc7711-fd1d-4d09-87c5-69a3ceb1ee28",
            "sourceColumn": "Consumption Type",
            "summarizeBy": "none"
          },
          {
            "name": "Sparkling vs. Non-Sparkling",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "941ae642-cea8-46eb-acc3-0b4cb82d0f23",
            "sourceColumn": "Sparkling vs. Non-Sparkling",
            "summarizeBy": "none"
          },
          {
            "name": "Beverage Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d619c8bd-5be1-4499-bf62-f860cba3cf3e",
            "sourceColumn": "Beverage Type",
            "summarizeBy": "none"
          },
          {
            "name": "Container",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c91ac471-2086-40f8-9c1f-38d2755a4662",
            "sourceColumn": "Container",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76cecd04-fbf4-42d8-8bb1-b7cc151d6f4c",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "CBR Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9af6d2b-0ba0-4673-a2cd-6e0a1da46252",
            "sourceColumn": "CBR Category",
            "summarizeBy": "none"
          },
          {
            "name": "Gains and Drains Combo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Product'[ELT Category] & \" / \" & 'Product'[Trademark] & \" / \" & 'Product'[Package]",
            "isDataTypeInferred": true,
            "lineageTag": "7cdc6d20-84bf-4bea-9d26-dbfa286cc3de",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "description": "rms_mdl vw_Dim_Category",
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "System Brands",
                "column": "System Brands",
                "lineageTag": "3a341a52-bca2-4554-9a09-18d9efe43d3a",
                "ordinal": 0
              },
              {
                "name": "Manufacturer",
                "column": "Manufacturer",
                "lineageTag": "c131e964-96bd-4259-826e-98469a474235",
                "ordinal": 1
              },
              {
                "name": "Trademark",
                "column": "Trademark",
                "lineageTag": "74e007a2-dd46-484d-b3dc-608230b8eb0b",
                "ordinal": 2
              },
              {
                "name": "Brand",
                "column": "Brand",
                "lineageTag": "8f971706-7f4a-44d6-88be-67f4f28a7cb9",
                "ordinal": 3
              }
            ],
            "lineageTag": "5125277d-8fe2-473c-be10-4581dd9c9223"
          }
        ],
        "lineageTag": "eca76a9c-6f40-43d2-a69e-bc43b35111b7",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    rms_mdl_vw_dim_product = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_product\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(rms_mdl_vw_dim_product,{\"manufacturer_hier_id\", \"ko_system_brands_id\", \"ko_key_manufacturer_id\", \"ko_key_flavor_id\", \"ko_key_trademark_id\", \"ko_key_brand_id\", \"category_hier_id\", \"ko_route_to_market_id\", \"ko_ccna_selected_beverage_category\", \"ko_ccna_selected_beverage_category_id\", \"ko_total_category_id\", \"ko_elt_category_id\", \"package_hier_id\", \"ko_consumption_id\", \"ko_sparkling_non_sparkling_id\", \"ko_beverage_type_id\", \"ko_container_id\", \"ko_key_package_id\", \"updatedtimestamp\", \"ko_business_review_category_id\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"product_key\", \"Product Key\"}, {\"ko_system_brands\", \"System Brands\"}, {\"ko_key_manufacturer\", \"Manufacturer\"}, {\"ko_key_flavor\", \"Flavor\"}, {\"ko_key_trademark\", \"Trademark\"}, {\"ko_key_brand\", \"Brand\"}, {\"ko_route_to_market\", \"Route-to-Market\"}, {\"ko_total_category\", \"Total Category\"}, {\"ko_elt_category\", \"ELT Category\"}, {\"ko_consumption\", \"Consumption Type\"}, {\"ko_sparkling_non_sparkling\", \"Sparkling vs. Non-Sparkling\"}, {\"ko_beverage_type\", \"Beverage Type\"}, {\"ko_container\", \"Container\"}, {\"ko_key_package\", \"Package\"}, {\"ko_business_review_category\", \"Business Review Category\"}}),",
                "  #\"Renamed Columns 1\" = Table.RenameColumns(#\"Renamed Columns\", {{\"Business Review Category\", \"CBR Category\"}})",
                "in",
                "    #\"Renamed Columns 1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7875d581-6a72-4edb-9b9a-33545985bd17",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Market Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "market_description",
            "isHidden": true,
            "lineageTag": "341b42c2-c976-4db0-a638-1172acfae1cc",
            "sourceColumn": "Market Description",
            "summarizeBy": "none"
          },
          {
            "name": "Corporation Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "corporation_total",
            "isHidden": true,
            "lineageTag": "4b34c102-7b86-46d9-9144-04e168ae2e01",
            "sourceColumn": "Corporation Total",
            "summarizeBy": "none"
          },
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e47383b2-9f5b-41d0-be5f-470b05ab899e",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b320128e-264f-4b13-b70c-7f2920a2439f",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_Dim_Customers",
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "levels": [
              {
                "name": "Corporation Total",
                "column": "Corporation Total",
                "lineageTag": "a621109d-86dc-4a23-9a68-4406af1719b0",
                "ordinal": 0
              },
              {
                "name": "Division",
                "column": "Division",
                "lineageTag": "e4483568-091e-416e-8c57-5fd58a77458a",
                "ordinal": 1
              },
              {
                "name": "Market Description",
                "column": "Market Description",
                "lineageTag": "4ef725b3-8f3a-4ed5-947a-7329dead0981",
                "ordinal": 2
              }
            ],
            "lineageTag": "d3dc046f-5799-4e1f-b506-549c98e9c34c"
          }
        ],
        "lineageTag": "535b64fa-f058-472f-837d-5a0841f48684",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    DnAIQDb_PreProd = Source{[Name=\"DnAIQDb_PreProd\"]}[Data],",
                "    rms_mdl_vw_Dim_Customers = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_customers\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_Dim_Customers,{{\"channel\", \"Channel\"}, {\"corporation_total\", \"Corporation Total\"}, {\"market_description\", \"Market Description\"}, {\"parent_market_description\", \"Parent Market Description\"}, {\"customer_key\", \"Customer Key\"}, {\"division\", \"Division\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Parent Market Description\", \"updatedtimestamp\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebe186b9-782d-4395-a7c7-e4e397d0d478",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "c729fe57-8a0c-4a00-b2db-d63867da7bea",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_year",
            "formatString": "0",
            "lineageTag": "0e57ac97-731b-41bd-8f4b-04b3ab92db4d",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_quarter",
            "isHidden": true,
            "lineageTag": "0b7d41a5-dbe5-4218-8fdd-ae2d225be39e",
            "sortByColumn": "Quarter Number",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_month",
            "isHidden": true,
            "lineageTag": "190fad6b-78be-4dda-9cb8-4811a71c4ac5",
            "sortByColumn": "Month Number",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "fiscal_week",
            "isHidden": true,
            "lineageTag": "c402ed21-2066-45b6-92e3-6af7b643b5a7",
            "sortByColumn": "Week Number",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_quarter",
            "lineageTag": "ef330159-1373-4d36-a61e-5b2b836c9359",
            "sortByColumn": "Sequential Quarter Number",
            "sourceColumn": "Fiscal Year Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_month",
            "lineageTag": "404519bd-d639-4c80-8431-1998d403d382",
            "sortByColumn": "Sequential Month Number",
            "sourceColumn": "Fiscal Year Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "description": "fiscal_year_week",
            "lineageTag": "4e839fcd-c091-4893-a868-d8d697ec5a44",
            "sortByColumn": "Sequential Week Number",
            "sourceColumn": "Fiscal Year Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_quarter_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "5bd75638-6233-4a0c-96d8-5eece4e2b5e2",
            "sourceColumn": "Fiscal Quarter Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_month_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "7837fc5a-2143-4bae-bc08-c7ab96501a9a",
            "sourceColumn": "Fiscal Month Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "fiscal_week_ending_date",
            "formatString": "mm/dd/yy",
            "isHidden": true,
            "lineageTag": "3c2b353b-8433-4f14-b77d-f7373ec75438",
            "sourceColumn": "Fiscal Week Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a15d9580-c371-4ebf-8020-655afa48b670",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c151a0eb-440a-4ef1-befe-b9a62caa9d87",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "week_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3f30187-a16a-439d-a687-e513c73ba0cc",
            "sourceColumn": "Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Sequential Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e5697b30-4a13-4f81-900b-fc316f9983a8",
            "sourceColumn": "Sequential Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Sequential Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d653e652-3bc4-4f22-befd-aa48bd503d63",
            "sourceColumn": "Sequential Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Sequential Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_week_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "216ac7e6-f6e2-4042-85ae-1c6f0577c8b9",
            "sourceColumn": "Sequential Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Sequential Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "sequential_day_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "052f0daf-51d9-49ba-8e37-d32516b99a2e",
            "sourceColumn": "Sequential Day Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Week In Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_week_in_quarter_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fed31204-4bc5-4875-ba15-5663cf122405",
            "sourceColumn": "Fiscal Week In Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Week In Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "description": "fiscal_week_in_month_number",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39a8fdeb-fa11-4054-8cd2-e2cb3e13fdf1",
            "sourceColumn": "Fiscal Week In Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Nielsen Week Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "description": "nielsen_week_ending_date",
            "formatString": "Short Date",
            "lineageTag": "9ba9e29f-c373-46f7-97b0-11e2b2d1bd3f",
            "sourceColumn": "Nielsen Week Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave",
            "isHidden": true,
            "lineageTag": "a90f1c54-5d66-4941-9fa2-e2b20927bbbc",
            "sourceColumn": "SOVI Wave",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_year",
            "isHidden": true,
            "lineageTag": "c99a884b-11ef-478d-ae37-7d5453092e2e",
            "sourceColumn": "SOVI Wave Year",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_number",
            "isHidden": true,
            "lineageTag": "aad521df-3687-4ac4-980e-adfe98890b7c",
            "sourceColumn": "SOVI Wave Number",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Sequential Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_sequential_number",
            "isHidden": true,
            "lineageTag": "7e692abf-568d-416e-866c-5dfc284eda55",
            "sourceColumn": "SOVI Sequential Number",
            "summarizeBy": "none"
          },
          {
            "name": "SOVI Wave Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "sovi_wave_ending_date",
            "isHidden": true,
            "lineageTag": "bdca21be-bb60-4716-ad39-8c0e82bf4995",
            "sourceColumn": "SOVI Wave Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "Current Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d91339c7-df9d-48a0-8870-7b4c4e361972",
            "sourceColumn": "Current Fiscal Period",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "description": "rms_mdl vw_Dim_Period",
        "hierarchies": [
          {
            "name": "Fiscal Hierarchy by Period Name",
            "levels": [
              {
                "name": "Fiscal Year",
                "column": "Fiscal Year",
                "lineageTag": "a271f563-a65a-4fa9-8bc2-59988db299af",
                "ordinal": 0
              },
              {
                "name": "Fiscal Quarter",
                "column": "Fiscal Quarter",
                "lineageTag": "3745e07f-6db8-41f5-8433-2393b2a8b1a1",
                "ordinal": 1
              },
              {
                "name": "Fiscal Month",
                "column": "Fiscal Month",
                "lineageTag": "d6e8e507-9626-4721-bf8a-961fb30c5410",
                "ordinal": 2
              },
              {
                "name": "Fiscal Week",
                "column": "Fiscal Week",
                "lineageTag": "f1ec5e04-8aa5-441c-b402-c280068e4862",
                "ordinal": 3
              }
            ],
            "lineageTag": "7f69d1c0-dd13-423a-9b29-b2a000c3666d"
          },
          {
            "name": "Fiscal Hierarchy by Ending Date",
            "levels": [
              {
                "name": "Fiscal Quarter Ending Date",
                "column": "Fiscal Quarter Ending Date",
                "lineageTag": "11894954-0807-4e37-b004-ce4338c2f433",
                "ordinal": 0
              },
              {
                "name": "Fiscal Month Ending Date",
                "column": "Fiscal Month Ending Date",
                "lineageTag": "8172cf10-3dd4-4fe2-9d18-b3d9ed0b5ccb",
                "ordinal": 1
              },
              {
                "name": "Fiscal Week Ending Date",
                "column": "Fiscal Week Ending Date",
                "lineageTag": "bf44aad1-83d6-47bf-88d5-a0dd184cdc11",
                "ordinal": 2
              }
            ],
            "lineageTag": "01027459-1a3e-4f7a-a5a4-3ae3b8dccc3c"
          }
        ],
        "lineageTag": "bf8ac801-920a-42f6-a059-686f7b0daaa1",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, Database),",
                "    DnAIQDb_PreProd = Source{[Name=\"DnAIQDb_PreProd\"]}[Data],",
                "    rms_mdl_vw_Dim_Period = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_period\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(rms_mdl_vw_Dim_Period,{{\"date\", type date}, {\"fiscal_quarter_ending_date\", type date}, {\"fiscal_month_ending_date\", type date}, {\"fiscal_week_ending_date\", type date}, {\"nielsen_week_ending_date\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"fiscal_month\", \"Fiscal Month\"}, {\"fiscal_month_ending_date\", \"Fiscal Month Ending Date\"}, {\"fiscal_quarter\", \"Fiscal Quarter\"}, {\"fiscal_quarter_ending_date\", \"Fiscal Quarter Ending Date\"}, {\"fiscal_week\", \"Fiscal Week\"}, {\"fiscal_week_ending_date\", \"Fiscal Week Ending Date\"}, {\"fiscal_week_in_month_number\", \"Fiscal Week In Month Number\"}, {\"fiscal_week_in_quarter_number\", \"Fiscal Week In Quarter Number\"}, {\"fiscal_year\", \"Fiscal Year\"}, {\"fiscal_year_month\", \"Fiscal Year Month\"}, {\"fiscal_year_quarter\", \"Fiscal Year Quarter\"}, {\"fiscal_year_week\", \"Fiscal Year Week\"}, {\"month_number\", \"Month Number\"}, {\"nielsen_week_ending_date\", \"Nielsen Week Ending Date\"}, {\"quarter_number\", \"Quarter Number\"}, {\"sequential_day_number\", \"Sequential Day Number\"}, {\"sequential_month_number\", \"Sequential Month Number\"}, {\"sequential_quarter_number\", \"Sequential Quarter Number\"}, {\"sequential_week_number\", \"Sequential Week Number\"}, {\"sovi_sequential_number\", \"SOVI Sequential Number\"}, {\"sovi_wave\", \"SOVI Wave\"}, {\"sovi_wave_ending_date\", \"SOVI Wave Ending Date\"}, {\"sovi_wave_number\", \"SOVI Wave Number\"}, {\"sovi_wave_year\", \"SOVI Wave Year\"}, {\"week_number\", \"Week Number\"}, {\"date\", \"Date\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Fiscal Year\", Int64.Type}, {\"Quarter Number\", Int64.Type}, {\"Month Number\", Int64.Type}, {\"Week Number\", Int64.Type}, {\"Sequential Quarter Number\", Int64.Type}, {\"Sequential Month Number\", Int64.Type}, {\"Sequential Week Number\", Int64.Type}, {\"Sequential Day Number\", Int64.Type}, {\"Fiscal Week In Quarter Number\", Int64.Type}, {\"Fiscal Week In Month Number\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"updatedtimestamp\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"date_key\", \"Date Key\"}, {\"current_fiscal_period\", \"Current Fiscal Period\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Share of Market (Bottler)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Bottler Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "42bd5d35-e9bb-4af3-aab1-15b588fa154d",
            "sourceColumn": "Bottler Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7e6c2508-ea9c-4acd-8c26-d1d7821da5c2",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Fields",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5759eb60-ffc5-4618-8a8b-e37c689c6502",
            "sourceColumn": "Product Key",
            "summarizeBy": "none"
          },
          {
            "name": "dollars_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "7ed3ea7e-095c-4da8-94ab-1d39408f77e7",
            "sourceColumn": "dollars_",
            "summarizeBy": "sum"
          },
          {
            "name": "eq_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "a0fed1d2-7ae7-42c8-92b7-d71ea510078e",
            "sourceColumn": "eq_",
            "summarizeBy": "sum"
          },
          {
            "name": "units_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden Fields",
            "isHidden": true,
            "lineageTag": "0bafa4bd-b8ed-45b2-982f-f2f039aefc3e",
            "sourceColumn": "units_",
            "summarizeBy": "sum"
          }
        ],
        "description": "rms_mdl vw_fact_bottlerweekly",
        "lineageTag": "03e4a23a-61b3-4478-94fd-9a1b2a638953",
        "measures": [
          {
            "name": "Dollars ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[dollars_])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "facfad3a-554d-4c40-ac53-141788647105"
          },
          {
            "name": "Units ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[units_])",
            "formatString": "#,0.00",
            "lineageTag": "2089255b-104a-4545-b6c7-2acda985a63b"
          },
          {
            "name": "EQs ",
            "displayFolder": "Base Measures",
            "expression": "SUM('Share of Market (Bottler)'[eq_])",
            "formatString": "#,0.00",
            "lineageTag": "7ed6079a-a7fe-48e6-a270-1297dc7c6dc8"
          },
          {
            "name": "Share of Dollars ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[Dollars ]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Dollars ],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Dollars ],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "lineageTag": "95429684-33e6-4a42-8833-6a6e66afa824"
          },
          {
            "name": "Share of Dollars YTD ",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars LW ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e06a5b23-49b5-4945-9a54-da430bc2940e"
          },
          {
            "name": "Share of Dollars YTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars YTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "b710081b-d01c-4de3-8275-a4875c0b2afe"
          },
          {
            "name": "Share of Dollars QTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2304d4c7-992f-4999-aa8a-ad5f816f9156"
          },
          {
            "name": "Share of Dollars R4W ",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8024b108-2670-48b8-ad34-aa203fd2bba2"
          },
          {
            "name": "Share of Dollars LW ",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "97dcfe20-a85c-4567-8d82-e79699779c3a"
          },
          {
            "name": "Share of Dollars R4W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R4W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "a1743198-e046-4b6e-91c6-6c8f7d44d25f"
          },
          {
            "name": "Share of Dollars LW vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars LW ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "63f5f38c-3ce7-4336-9eb2-6add6970df11"
          },
          {
            "name": "Share of Dollars QTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars QTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "18a0826b-56c4-4e88-9949-d50aae8e9f3b"
          },
          {
            "name": "YoY Share of Dollars (% pts) ",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Dollars LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of Dollars MTD vs. PY (% pts) ],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of Dollars QTD vs. PY (% pts) ],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of Dollars YTD vs. PY (% pts) ]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "bc43296b-e6d4-4540-a5f7-2a0bee941df3"
          },
          {
            "name": "Share of Dollars MTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cd57226f-df09-466a-beef-0ab876e467bc"
          },
          {
            "name": "Share of Dollars MTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars MTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "856d70c8-641e-451d-ba95-40c290c98511"
          },
          {
            "name": "Share of Dollars R13W ",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3abdb717-308e-4ff5-a0b0-f1a758bf9878"
          },
          {
            "name": "Share of Dollars R13W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R13W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "805a8687-a8ec-411a-844d-e8b51ffe795b"
          },
          {
            "name": "Share of Dollars R52W ",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fc6d7239-ffdc-477c-b8a1-ca2f102b2774"
          },
          {
            "name": "Share of Dollars R52W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Dollars",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Dollars ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R52W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "0a0d07b6-cc3d-465f-9626-5b9108c807e7"
          },
          {
            "name": "Share of Units ",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[Units ]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Units ],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Units ],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4c6a920b-5abb-4732-9571-f74ffc5e54aa"
          },
          {
            "name": "Share of Units YTD ",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a35fb4f0-3382-44eb-975c-434d3a1800f6"
          },
          {
            "name": "Share of Units YTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units YTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "90a76fb0-bd88-46dc-9817-b0665e2fcc8e"
          },
          {
            "name": "Share of Units QTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0f270aaa-1301-4c82-900d-442db5a7f4df"
          },
          {
            "name": "Share of Units R4W ",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d68dff1e-6098-4f59-8485-ce203575be7a"
          },
          {
            "name": "Share of Units LW ",
            "description": "Share over the Last Week",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "54d8a227-8d57-48bc-9c2d-ce269b08dd5e"
          },
          {
            "name": "Share of Units R4W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R4W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "493009d7-dd7c-48c3-9f54-3c064fd0e82c"
          },
          {
            "name": "Share of Units LW vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units LW ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "47b3b661-00e0-47b5-892c-a72724916eed"
          },
          {
            "name": "Share of Units QTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars QTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "ece304ae-34e1-4342-816d-8f60df46d010"
          },
          {
            "name": "YoY Share of Units (% pts) ",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of Units LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of Units MTD vs. PY (% pts) ],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of Units QTD vs. PY (% pts) ],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of Units YTD vs. PY (% pts) ]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "a74977c4-35ac-40f9-b3d0-9e156d57f0fb"
          },
          {
            "name": "Share of Units MTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "09ce3802-91c9-4caa-9b79-0d89acc8bd7f"
          },
          {
            "name": "Share of Units MTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units MTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "d516b7d4-4850-4e82-ab82-995a3f470b9b"
          },
          {
            "name": "Share of Units R13W ",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b17bf0fe-2fa3-4304-99b9-458f7ce1a127"
          },
          {
            "name": "Share of Units R13W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R13W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "47ef3cd2-0979-4536-8723-2538add6f7bc"
          },
          {
            "name": "Share of Units R52W ",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0f249169-e923-46e6-91e4-d2af0dbb52b6"
          },
          {
            "name": "Share of Units R52W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of Units",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of Units ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Units R52W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "5dab37a5-5d80-4d0d-aa9f-1022d9bf7384"
          },
          {
            "name": "Share of EQs ",
            "description": "Share is calculated against Total Beverage when viewing by 'System Brands' or 'Manufacturer', and is calculated against ELT Category when viewing by 'Trademark' or 'Brand'",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "/*",
              "Share of dollars is using the same DAX as SOVI from iRED Explorer.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total dollars for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total dollars for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total dollars for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "*/",
              "",
              "VAR selected_total = 'Share of Market (Bottler)'[EQs ]",
              "",
              "VAR category_total =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[EQs ],",
              "        VALUES ( 'Product'[ELT Category] ),",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR total_beverage =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[EQs ],",
              "        ALLEXCEPT('Product','Product'[ELT Category])",
              "    )",
              "",
              "VAR category_share =",
              "    DIVIDE ( selected_total, category_total )",
              "    ",
              "VAR total_beverage_share =",
              "    DIVIDE ( selected_total, total_beverage )",
              "",
              "VAR results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Product'[Brand] ), category_share,",
              "        HASONEFILTER ( 'Product'[Trademark] ), category_share,",
              "        HASONEFILTER ( 'Product'[Manufacturer] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[System Brands] ), total_beverage_share,",
              "        HASONEFILTER ( 'Product'[Gains and Drains Combo] ), category_share,",
              "        1",
              "    )",
              "    ",
              "RETURN",
              "    results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "46d8b910-727a-4061-98c3-0e93c3f12729"
          },
          {
            "name": "Share of EQs YTD ",
            "description": [
              "Share for Year-to-Date",
              ""
            ],
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR ytd_year = MAX('Calendar'[Fiscal Year])",
              "",
              "//this variable gets the latest week in the latest year",
              "VAR ytd_week = MAX('Calendar'[Week Number])",
              "",
              "//this variable gets the results",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year,",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a78ce3c9-7737-4053-b2d2-b0df40640c78"
          },
          {
            "name": "Share of EQs YTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//these variables help to filter by the calendar",
              "VAR ytd_year_cy = max('Calendar'[Fiscal Year])",
              "VAR ytd_year_py = max('Calendar'[Fiscal Year]) - 1",
              "VAR ytd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Week Number]),",
              "        'Calendar'[Fiscal Year] = ytd_year_cy)",
              "",
              "//this next variable gets the PY Value",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Fiscal Year] = ytd_year_py, ",
              "        'Calendar'[Week Number] <= ytd_week",
              "    )",
              "",
              "//this variable gets the existing measure for the CY share",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs YTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "2f07ec7f-0cd4-4621-85bf-7642507ebbd7"
          },
          {
            "name": "Share of EQs QTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest quarter",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_cy, ",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ad93e5dc-79c7-4005-8eee-449008656579"
          },
          {
            "name": "Share of EQs R4W ",
            "description": "Share over a rolling 4 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d2cc4b96-777b-4706-84cb-0e10739fd4b0"
          },
          {
            "name": "Share of EQs LW ",
            "description": "Share over the Last Week",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "",
              "//this variable to find the last week",
              "VAR lcw = MAX('Calendar'[Sequential Week Number]) ",
              "",
              "//this variable calculates the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        'Calendar'[Sequential Week Number] = lcw",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "50951ca5-86ae-46c8-9f48-77d7d6d37975"
          },
          {
            "name": "Share of EQs R4W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 4",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs R4W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "2a134104-bd41-4aff-a2b1-7926a1c388d4"
          },
          {
            "name": "Share of EQs LW vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable to identify the same time period of the prior year",
              "VAR lcw_py = max('Calendar'[Sequential Week Number]) - 52",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results = ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] = lcw_py",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs LW ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "530eec1a-3c84-4f2e-b8ec-86656649b835"
          },
          {
            "name": "Share of EQs QTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the latest year",
              "VAR qtd_cy = max('Calendar'[Sequential Quarter Number]) ",
              "",
              "//this variable gets the latest year",
              "VAR qtd_py = qtd_cy - 4",
              "",
              "//get the max week within the latest quarter",
              "VAR qtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Quarter Number]),",
              "         'Calendar'[Sequential Quarter Number] = qtd_cy",
              "    )",
              "",
              "//this variable gets the results",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Quarter Number] = qtd_py,",
              "        'Calendar'[Fiscal Week in Quarter Number] <= qtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs QTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "07fdd95b-0c68-4feb-97b4-d920251dffd1"
          },
          {
            "name": "YoY Share of EQs (% pts) ",
            "description": "This measure is meant to be used against a calendar hierarchy",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this variable gets the share calculation for the appropriate time period",
              "VAR results = ",
              "    SWITCH(",
              "        TRUE,",
              "        OR(ISINSCOPE('Calendar'[Fiscal Week]),ISINSCOPE('Calendar'[Fiscal Week Ending Date])), [Share of EQs LW vs. PY (% pts)],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Month]),ISINSCOPE('Calendar'[Fiscal Month Ending Date])), 'Share of Market (Bottler)'[Share of EQs MTD vs. PY (% pts) ],",
              "        OR(ISINSCOPE('Calendar'[Fiscal Quarter]),ISINSCOPE('Calendar'[Fiscal Quarter Ending Date])), 'Share of Market (Bottler)'[Share of EQs QTD vs. PY (% pts) ],",
              "        ISINSCOPE('Calendar'[Fiscal Year]), 'Share of Market (Bottler)'[Share of EQs YTD vs. PY (% pts) ]",
              "    )",
              "    ",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "a3cb9db2-96ea-452d-a82b-c69015d7ecfd"
          },
          {
            "name": "Share of EQs MTD ",
            "description": "Share over Quarter-to-Date",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number]) ",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        max('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_cy, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "988a78ec-da8d-4d9a-9e4b-35c11e821683"
          },
          {
            "name": "Share of EQs MTD vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//get the latest month",
              "VAR mtd_cy = max('Calendar'[Sequential Month Number])",
              "",
              "//get the latest month for the same time last year",
              "VAR mtd_py = max('Calendar'[Sequential Month Number]) - 12",
              "",
              "//get the max week within the latest month",
              "VAR mtd_week = ",
              "    CALCULATE(",
              "        MAX('Calendar'[Fiscal Week in Month Number]),",
              "         'Calendar'[Sequential Month Number] = mtd_cy",
              "    )",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE(",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Month Number] = mtd_py, ",
              "        'Calendar'[Fiscal Week in Month Number] <= mtd_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs MTD ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "478e33e0-9b2a-4993-ad12-0adc7c2d2dfc"
          },
          {
            "name": "Share of EQs R13W ",
            "description": "Share over a rolling 13 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5010edfb-157e-415f-b168-fed97295e65d"
          },
          {
            "name": "Share of EQs R13W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 13",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of EQs R13W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "5c3f8ece-3b20-466d-9ed9-e7f4782a2f2d"
          },
          {
            "name": "Share of EQs R52W ",
            "description": "Share over a rolling 52 week period",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week, which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] )",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to calculate the results",
              "VAR results =",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d60b17cc-feed-452e-a9ba-9de0cc8350a2"
          },
          {
            "name": "Share of EQs R52W vs. PY (% pts) ",
            "description": "The difference in 'Percentage Points' between the Current Year and the Previous Year over the same weeks",
            "displayFolder": "Share of EQs",
            "expression": [
              "",
              "//this varible will define the number of weeks in the rolling calculation",
              "VAR number_of_rolling_weeks = 52",
              "",
              "//this variable to find the last week from 1 year ago (aka 52 weeks), which is the end week of the query range",
              "VAR end_week = MAX ( 'Calendar'[Sequential Week Number] ) - 52",
              "",
              "//this variable to find 4 weeks ago, which is the start week of the query range",
              "VAR start_week = end_week - number_of_rolling_weeks",
              "",
              "//this variable to get the share results for the same time period of the prior year",
              "VAR py_results =  ",
              "    CALCULATE (",
              "        'Share of Market (Bottler)'[Share of EQs ],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Sequential Week Number] > start_week,",
              "        'Calendar'[Sequential Week Number] <= end_week",
              "    )",
              "",
              "//this variable gets the share results for the current year ",
              "VAR cy_results = 'Share of Market (Bottler)'[Share of Dollars R52W ]",
              "",
              "//this variable calculates the final results",
              "VAR results = ",
              "    IF(",
              "        ISBLANK(py_results),",
              "        BLANK(),",
              "        (cy_results - py_results)*100",
              "    )",
              "",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "19f41e24-1537-4fde-af92-2290348090a0"
          }
        ],
        "partitions": [
          {
            "name": "Share of Market (Bottler)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Server\", #\"Database\"),",
                "    rms_mdl_vw_fact_bottlerweekly = Source{[Schema=\"rms_mdl\",Item=\"vw_fact_bottlerweekly\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_fact_bottlerweekly,{{\"bottler_key\", \"Bottler Key\"}, {\"date_key\", \"Date Key\"}, {\"product_key\", \"Product Key\"}, {\"dollars\", \"dollars_\"}, {\"eq\", \"eq_\"}, {\"units\", \"units_\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Bottler",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Bottler Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31a6c29b-fcfa-4eae-9fa7-cf7073452479",
            "sourceColumn": "Bottler Key",
            "summarizeBy": "none"
          },
          {
            "name": "Market Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7fcd0d2e-a3d6-473f-9b42-2d7321c5c6ff",
            "sourceColumn": "Market Description",
            "summarizeBy": "none"
          },
          {
            "name": "Bottler",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320d729c-8954-4049-b11d-1937183c0a95",
            "sourceColumn": "Bottler",
            "summarizeBy": "none"
          },
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80748c1c-ccf7-4767-a06a-6511c2225281",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ce9b7ec6-44c9-4371-affa-65fa41b313de",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          }
        ],
        "description": "rms_mdl vw_dim_bottlers",
        "hierarchies": [
          {
            "name": "Bottler Hierarchy",
            "levels": [
              {
                "name": "Bottler",
                "column": "Bottler",
                "lineageTag": "934bedb8-91cf-40f2-b139-67cc8dc92a07",
                "ordinal": 0
              },
              {
                "name": "Division",
                "column": "Division",
                "lineageTag": "6f7b3bb3-49b2-44cb-9b4d-4739ee8ed0ef",
                "ordinal": 1
              },
              {
                "name": "Market Description",
                "column": "Market Description",
                "lineageTag": "fec63eee-c4ce-4b79-8ab6-03b3c88ad32a",
                "ordinal": 2
              }
            ],
            "lineageTag": "bd930c9c-7668-489d-badc-2d5c1a1ef915"
          }
        ],
        "lineageTag": "4e1d402f-0c1f-486a-b4fa-fae684de827c",
        "partitions": [
          {
            "name": "Bottler",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Server\", #\"Database\"),",
                "    rms_mdl_vw_dim_bottlers = Source{[Schema=\"rms_mdl\",Item=\"vw_dim_bottlers\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(rms_mdl_vw_dim_bottlers,{{\"bottler\", \"Bottler\"}, {\"channel\", \"Channel\"}, {\"market_description\", \"Market Description\"}, {\"parent_market_description\", \"Parent Market Description\"},{\"bottler_key\", \"Bottler Key\"}, {\"division\", \"Division\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"updatedtimestamp\", \"Parent Market Description\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}