{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Product\",\"iRED Measures\",\"Store Area\",\"Outlet\",\"Server\",\"DataBase\",\"Calendar\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"WebModelingEdit\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Server",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syn-tccc-udp-dnao-us2-prd-01-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "1e2cde0b-937a-4fa2-81ae-826bb58064e3"
      },
      {
        "name": "DataBase",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"DnAIQDb\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "31fbafaf-7558-4b65-a894-b0194db0262f"
      }
    ],
    "relationships": [
      {
        "name": "51678c4a-e9e9-4941-908d-0903d117229e",
        "fromColumn": "productid",
        "fromTable": "iRED Measures",
        "toColumn": "productid",
        "toTable": "Product"
      },
      {
        "name": "6f84fd32-68e8-44c4-9fcc-6cb3817f8663",
        "fromColumn": "outlet_key",
        "fromTable": "iRED Measures",
        "toColumn": "outlet_key",
        "toTable": "Outlet"
      },
      {
        "name": "794c4f9c-ac3e-4da9-a8be-6a1ba45216b1",
        "fromColumn": "sub_location_code",
        "fromTable": "iRED Measures",
        "toColumn": "Sub_Location_Code",
        "toTable": "Store Area"
      },
      {
        "name": "92c3ce5a-a508-25f4-b3ff-5a67fb0c3db9",
        "fromColumn": "Visit Date",
        "fromTable": "iRED Measures",
        "toColumn": "Vist Date",
        "toTable": "Calendar"
      }
    ],
    "roles": [
      {
        "name": "EndUsers",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f2dfac65fb2b4fa1b9a35bdab1d79b26"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Calendar",
            "filterExpression": "'Calendar'[wave_ending_date] <= NOW()"
          }
        ]
      },
      {
        "name": "Admin",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "89691b6ba6884863a89303d33ed1f92b"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Calendar",
            "filterExpression": "'Calendar'[wave_ending_date] >= dt\"2022-01-01\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "productid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "ed78d67f-eb18-4e36-b287-d92676c4160a",
            "sourceColumn": "productid",
            "summarizeBy": "none"
          },
          {
            "name": "RTM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "KO Route To Market",
            "lineageTag": "ebedcfcc-ed78-460d-8c13-b2e6d6c41abb",
            "sourceColumn": "RTM",
            "summarizeBy": "none"
          },
          {
            "name": "ko_elt_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": [
              "ELT Category",
              ""
            ],
            "isHidden": true,
            "lineageTag": "119fd8d5-ca74-4aa7-938a-20669010d101",
            "sourceColumn": "ko_elt_category",
            "summarizeBy": "none"
          },
          {
            "name": "ko_perf_mgmt_sub_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "324d48a5-6138-40c3-8832-8eb94f98afa0",
            "sourceColumn": "ko_perf_mgmt_sub_category",
            "summarizeBy": "none"
          },
          {
            "name": "ko_consumption",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2660eaca-9e01-41e7-8990-b5b593c57bee",
            "sourceColumn": "ko_consumption",
            "summarizeBy": "none"
          },
          {
            "name": "CBR Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "CBR category",
            "lineageTag": "80211cf5-7c22-4730-976c-c5f088a2337d",
            "sourceColumn": "CBR Category",
            "summarizeBy": "none"
          },
          {
            "name": "ko_key_manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "KO Key Manufacturer",
            "isHidden": true,
            "lineageTag": "fa4a5d24-fbf4-4d64-9c85-b2c624d559be",
            "sourceColumn": "ko_key_manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "ko_key_trademark",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "KO Key Trademark",
            "isHidden": true,
            "lineageTag": "67fa8a2e-f420-477e-b3da-f75197a00723",
            "sourceColumn": "ko_key_trademark",
            "summarizeBy": "none"
          },
          {
            "name": "ko_key_brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "729269da-4418-4139-86a2-1192e6f027e0",
            "sourceColumn": "ko_key_brand",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecaea3cb-6773-4144-bfbb-1bcea9ae523c",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "Flavor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "20770192-cf4f-42b2-b8fd-f37140cfb77a",
            "sourceColumn": "Flavor",
            "summarizeBy": "none"
          },
          {
            "name": "ko_system_brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "KO System Brands",
            "isHidden": true,
            "lineageTag": "8dcb6636-cb7e-421f-93be-d9ebb76fe542",
            "sourceColumn": "ko_system_brands",
            "summarizeBy": "none"
          },
          {
            "name": "SSD/Still",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "SSD IC, SSD FC from CBR category, and Core Sparkling from ELT are grouped as SSD all other categories are grouped as Still",
            "lineageTag": "2bcce0a3-85c3-4d5b-99cc-872113ed790b",
            "sourceColumn": "SSD/Still",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "System Brands",
                "column": "ko_system_brands",
                "lineageTag": "b1ecf1e4-5499-46b5-aeac-7935a610a240",
                "ordinal": 0
              },
              {
                "name": "Manufacturer",
                "column": "ko_key_manufacturer",
                "lineageTag": "c8c3f886-bf5a-497d-9b44-ec30766ed8c9",
                "ordinal": 1
              },
              {
                "name": "Trademark",
                "column": "ko_key_trademark",
                "lineageTag": "b7c8c746-e3b7-4d52-85a1-174f30c5fc03",
                "ordinal": 2
              },
              {
                "name": "Brand",
                "column": "ko_key_brand",
                "lineageTag": "aee67e95-fa1a-4e40-a58a-2de5fd32d3f1",
                "ordinal": 3
              }
            ],
            "lineageTag": "0adff979-0bba-4562-a78c-13ae2e4fb823"
          },
          {
            "name": "Category Hierarchy",
            "levels": [
              {
                "name": "Category",
                "column": "ko_elt_category",
                "lineageTag": "c72c21b1-c5c5-453a-a041-e7b3343f5228",
                "ordinal": 0
              },
              {
                "name": "Sub Category",
                "column": "ko_perf_mgmt_sub_category",
                "lineageTag": "bb843ee8-d7e3-42c0-b211-ac4b1988f132",
                "ordinal": 1
              }
            ],
            "lineageTag": "6f06865f-5967-40c7-9f18-26b5c56e7780"
          }
        ],
        "lineageTag": "1352c485-0f1c-4403-bba4-2738b0444eff",
        "partitions": [
          {
            "name": "Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, DataBase),",
                "    ired_mdl_vw_dim_product = Source{[Schema=\"ired_mdl\",Item=\"vw_dim_product\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(ired_mdl_vw_dim_product,{{\"ko_key_flavor\", \"Flavor\"}, {\"ko_business_review_category\", \"CBR Category\"}, {\"ko_route_to_market\", \"RTM\"}, {\"ko_key_package\", \"Package\"}, {\"sparkling_still\", \"SSD/Still\"}}),",
                "  #\"Renamed Columns 1\" = Table.RenameColumns(#\"Renamed Columns\", {{\"ko_key_trademark\", \"Trademark\"}}),",
                "  #\"Renamed Columns 2\" = Table.RenameColumns(#\"Renamed Columns 1\", {{\"Trademark\", \"ko_key_trademark\"}})",
                "in",
                "    #\"Renamed Columns 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "iRED Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "productid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Measures",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "53031e5c-89cf-40aa-9e4e-27b0ffb1c237",
            "sourceColumn": "productid",
            "summarizeBy": "none"
          },
          {
            "name": "bottler_ownership_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Measures",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62670817-12cf-4aa9-8c40-4505b18dafa6",
            "sourceColumn": "bottler_ownership_id",
            "summarizeBy": "sum"
          },
          {
            "name": "bottler_delivery_point_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden Measures",
            "isHidden": true,
            "lineageTag": "2daf32be-b9b4-4c9f-a230-d0b909958429",
            "sourceColumn": "bottler_delivery_point_number",
            "summarizeBy": "none"
          },
          {
            "name": "outlet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Measures",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a04cdfb6-ad26-4aa6-a770-e2f34305affb",
            "sourceColumn": "outlet_key",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Hidden Measures",
            "formatString": "m/d/yyyy",
            "isHidden": true,
            "lineageTag": "3202e030-efd0-4b08-a93d-63783f73a7d6",
            "sourceColumn": "Visit Date",
            "summarizeBy": "none"
          },
          {
            "name": "session_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden Measures",
            "isHidden": true,
            "lineageTag": "109fb4e5-ffd9-4f29-973d-663e72cd8300",
            "sourceColumn": "session_id",
            "summarizeBy": "none"
          },
          {
            "name": "scene_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden Measures",
            "isHidden": true,
            "lineageTag": "d24f9489-8783-4419-a909-85191d63eb8b",
            "sourceColumn": "scene_id",
            "summarizeBy": "none"
          },
          {
            "name": "facing",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Measures",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c62d3c3-a685-46c8-b192-5e2001cb1074",
            "sourceColumn": "facing",
            "summarizeBy": "sum"
          },
          {
            "name": "sub_location_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden Measures",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7e5c80e9-3fa5-4459-be6f-c8cf0fc675da",
            "sourceColumn": "sub_location_code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "45591597-13b7-43aa-893a-9e4d974df083",
        "measures": [
          {
            "name": "Availability",
            "displayFolder": "Actual",
            "expression": [
              "",
              "(",
              "    DIVIDE(",
              "        DISTINCTCOUNT('iRED Measures'[session_id]),",
              "        [Sample Size]",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "815a6094-949d-4c1c-bdf6-5097f8d9c716"
          },
          {
            "name": "Sample Size",
            "displayFolder": "Actual",
            "expression": [
              "",
              "CALCULATE(",
              "        DISTINCTCOUNT('iRED Measures'[session_id]),",
              "        ALL('Product'),",
              "        ALL('Store Area')",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "214510d7-e50b-497a-ad21-4a0441be09f2"
          },
          {
            "name": "Total # of Facings",
            "displayFolder": "Actual",
            "expression": [
              "",
              "SUMX ( 'iRED Measures', 'iRED Measures'[facing] )"
            ],
            "formatString": "#,0",
            "lineageTag": "ef2c9596-ed5b-4ee5-a29c-f9c4754c0255"
          },
          {
            "name": "Total # of SKUs",
            "displayFolder": "Actual",
            "expression": [
              "",
              "DISTINCTCOUNT('iRED Measures'[productid])"
            ],
            "formatString": "#,0",
            "lineageTag": "4e2ef1bd-65aa-49c8-8bbf-06f9971351b9"
          },
          {
            "name": "Average # of SKUs",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actual",
            "expression": [
              "",
              "DIVIDE ( [Total # of SKUs], [Sample Size] )"
            ],
            "formatString": "#,0.0",
            "lineageTag": "0fb01914-8a24-4590-bae9-7a10655fc34a"
          },
          {
            "name": "Average # of Facings per Survey",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "The number of facings divided by the sample size.",
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "DIVIDE ( [Total # of Facings], [Sample Size] )",
              ""
            ],
            "formatString": "#,0.0",
            "isHidden": true,
            "lineageTag": "5b791f05-6f4a-45e0-a458-5c73673f4a15"
          },
          {
            "name": "SOVI",
            "displayFolder": "Actual",
            "expression": [
              "",
              "",
              "/*",
              "The SOVI measure calculates the share of visual inventory.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total facings for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total facings for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total facings for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "",
              "SOVI must be filtered by at least one field in the Product Hierarchy. If you filter by System Brands or Manufacturer, SOVI is calculated against all beverage categories. If you filter by Trademark or Brand, SOVI is calculated against only the categories that the products fall under.",
              "*/",
              "",
              "VAR Total_Facings = [Total # of Facings]",
              "VAR Category_Total_Facings =",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        VALUES ( 'Product'[ko_elt_category] ),",
              "        ALL (",
              "            'Product'[ko_system_brands],",
              "            'Product'[ko_key_manufacturer],",
              "            'Product'[ko_key_trademark],",
              "            'Product'[ko_key_brand]",
              "        )",
              "    )",
              "VAR Total_Beverage_Facings =",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        ALL ( 'Product'[ko_system_brands], 'Product'[ko_key_manufacturer] )",
              "    )",
              "VAR Category_Share =",
              "    DIVIDE ( Total_Facings, Category_Total_Facings )",
              "VAR Total_Beverage_Share =",
              "    DIVIDE ( Total_Facings, Total_Beverage_Facings )",
              "VAR Results =",
              "    SWITCH (TRUE(),",
              "    ISFILTERED('Product'[ko_key_brand]), Category_Share, ",
              "    ISFILTERED('Product'[ko_key_trademark]), Category_Share,",
              "    ISFILTERED('Product'[ko_key_manufacturer]), Total_Beverage_Share,",
              "    ISFILTERED('Product'[ko_system_brands]), Total_Beverage_Share, 1",
              "    )",
              "RETURN",
              "    Results",
              ""
            ],
            "formatString": "0.0000%;-0.0000%;0.0000%",
            "lineageTag": "64543d90-29cc-4685-8546-271a38cfb505"
          },
          {
            "name": "Average # of Facings",
            "displayFolder": "Actual",
            "expression": [
              "",
              "",
              "VAR total_facings = [Total # of Facings]",
              "",
              "VAR total_stores = DISTINCTCOUNT('iRED Measures'[outlet_key])",
              "",
              "VAR results = DIVIDE(total_facings, total_stores)",
              "",
              "RETURN results"
            ],
            "formatString": "0.0",
            "lineageTag": "c506108f-482a-4fdd-a5a3-978bc74275c7"
          },
          {
            "name": "Average # of Displays",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Actual",
            "expression": [
              "",
              " ",
              "VAR _AvgDisplaysFiltered =",
              " ",
              "IF (",
              "    ISFILTERED('Store Area'[Location]) && VALUES('Store Area'[Location]) = \"Display\",",
              "    DIVIDE (",
              "        CALCULATE (",
              "            DISTINCTCOUNT ( 'iRED Measures'[scene_id] ),",
              "            FILTER('Store Area', 'Store Area'[Location] = \"Display\")",
              "        ),",
              "        [Sample Size]",
              "    ),",
              "    0",
              ")",
              " ",
              "VAR _AvgDisplays =",
              "DIVIDE (",
              "        CALCULATE (",
              "            DISTINCTCOUNT ( 'iRED Measures'[scene_id] ),",
              "            FILTER('Store Area', 'Store Area'[Location] = \"Display\")",
              "        ),",
              "        [Sample Size]",
              "    )",
              " ",
              "VAR _Results =",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Store Area'[location]), _AvgDisplaysFiltered,",
              "    _AvgDisplays",
              " ",
              ")",
              " ",
              "RETURN",
              "_Results",
              ""
            ],
            "lineageTag": "5c288e53-61b7-4d2a-bc03-4c1986a459cd"
          },
          {
            "name": "Average # of Coolers",
            "displayFolder": "Actual",
            "expression": [
              "/* decimal, 2 decimal points, show to user */",
              "VAR _AvgCoolersFiltered =",
              "    IF (",
              "        ISFILTERED ( 'Store Area'[Sub_Location] )",
              "            && LEFT ( SELECTEDVALUE ( 'Store Area'[Sub_Location] ), 6 ) = \"Cooler\",",
              "        DIVIDE (",
              "            CALCULATE (",
              "                DISTINCTCOUNT ( 'iRED Measures'[scene_id] ),",
              "                FILTER ( 'Store Area', LEFT ( 'Store Area'[Sub_Location], 6 ) = \"Cooler\" )",
              "            ),",
              "            [Sample Size]",
              "        ),",
              "        0",
              "    )",
              "VAR _AvgCoolers =",
              "    DIVIDE (",
              "        CALCULATE (",
              "            DISTINCTCOUNT ( 'iRED Measures'[scene_id] ),",
              "            FILTER ( 'Store Area', LEFT ( 'Store Area'[Sub_Location], 6 ) = \"Cooler\" )",
              "        ),",
              "        [Sample Size]",
              "    )",
              "VAR _Results =",
              "    SWITCH (",
              "        TRUE (),",
              "        HASONEFILTER ( 'Store Area'[Sub_Location] ), _AvgCoolersFiltered,",
              "        _AvgCoolers",
              "    )",
              "RETURN",
              "    _Results"
            ],
            "formatString": "#,##0.00",
            "lineageTag": "1e6c58f3-4673-4717-a3e0-5207afcfa915"
          },
          {
            "name": "SOVI CW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal place; hide from user view */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [SOVI],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "37b01ad6-53c3-425d-84b2-ea63e7644f93"
          },
          {
            "name": "SOVI PW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal place; hide from user view */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [SOVI],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "87fd48ee-5150-4c41-ad08-d7a4709dfab8"
          },
          {
            "name": "SOVI PY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal place; hide from user view */",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [SOVI],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "be04987e-81a5-44c8-bad6-80913fe1fb46"
          },
          {
            "name": "SOVI vs PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Decimal number with 2 decimal places; show to user */",
              "    IF(",
              "        OR(ISBLANK([SOVI PW]),ISBLANK([SOVI CW])),",
              "        BLANK(),",
              "        ([SOVI CW]-[SOVI PW])*100",
              "    )",
              ""
            ],
            "lineageTag": "d54eb584-4c9a-4d9b-b761-21d56e0ef3cf"
          },
          {
            "name": "SOVI vs PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Decimal number with 2 decimal places; show to user */",
              "    IF(",
              "        OR(ISBLANK([SOVI PY]),ISBLANK([SOVI CW])),",
              "        BLANK(),",
              "        ([SOVI CW]-[SOVI PY])*100",
              "    )",
              ""
            ],
            "lineageTag": "5d65b13c-46fa-4c43-8e29-b71701195454"
          },
          {
            "name": "Total # of SKUs CW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Whole number, 0 decimal places, comma for thousands separator, hide from user */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Total # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c82a6a85-4365-429d-970c-ae1bfb924813"
          },
          {
            "name": "Total # of SKUs PW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Whole number, 0 decimal places, comma for thousands separator, hide from user */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Total # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fad0660e-3677-4fce-b733-175f5de072d7"
          },
          {
            "name": "Total # of SKUs PY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Whole number, 0 decimal places, comma for thousands separator, hide from user */",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Total # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "6a316322-3282-446a-82be-2920185aef73"
          },
          {
            "name": "Total # of SKUs vs PW",
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Percentage, 1 decimal place, show to user */",
              "    IF(",
              "        OR(ISBLANK([Total # of SKUs PW]),ISBLANK([Total # of SKUs CW])),",
              "        BLANK(),",
              "        DIVIDE([Total # of SKUs CW]-[Total # of SKUs PW],[Total # of SKUs PW])",
              "    )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "577c7cc8-383b-4edd-8e0f-0d646e2b3239"
          },
          {
            "name": "Total # of SKUs vs PY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Percentage, 1 decimal place, show to user */",
              "    IF(",
              "        OR(ISBLANK([Total # of SKUs PY]),ISBLANK([Total # of SKUs])),",
              "        BLANK(),",
              "        DIVIDE([Total # of SKUs]-[Total # of SKUs PY],[Total # of SKUs PY])",
              "    )",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "04bee254-932a-4380-8acc-8ea33b3cb4c6"
          },
          {
            "name": "Average # of SKUs CW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "c505c307-ff17-4eec-bb39-aa9908850fab"
          },
          {
            "name": "Average # of SKUs PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "3978b27c-ba8c-40ce-8453-87768e526fda"
          },
          {
            "name": "Average # of SKUs PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of SKUs],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "fcc5881b-037b-4499-bada-c84ee360d14f"
          },
          {
            "name": "Average # of SKUs vs PW",
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Percentage with 1 decimal place, show to user */",
              "    IF(",
              "        OR(ISBLANK([Average # of SKUs PW]),ISBLANK([Average # of SKUs CW])),",
              "        BLANK(),",
              "        divide([Average # of SKUs CW]-[Average # of SKUs PW],[Average # of SKUs PW])",
              "    )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0cbf8d00-6397-42c2-b950-4272ff5b6439"
          },
          {
            "name": "Average # of SKUs vs PY",
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Percentage with 1 decimal place, show to user */",
              "    IF(",
              "        OR(ISBLANK([Average # of SKUs PY]),ISBLANK([Average # of SKUs CW])),",
              "        BLANK(),",
              "        DIVIDE([Average # of SKUs CW]-[Average # of SKUs PY],[Average # of SKUs PY])",
              "    )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a5259b89-d729-477f-a4ba-74a842b763e1"
          },
          {
            "name": "Average # of Facings CW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place; hide from user */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Facings],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "487d5cca-a359-416a-b520-adcc3f5bdcb6"
          },
          {
            "name": "Average # of Facings PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place; hide from user */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Facings],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "6f708f44-cd42-43fa-8eea-6dc4adc0fcab"
          },
          {
            "name": "Average # of Facings PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place; hide from user */",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Facings],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "c2efdf48-21c7-43d0-95dc-bdd09c4e6060"
          },
          {
            "name": "Average # of Facings vs PW",
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Percentage with 1 decimal place; show to user */",
              "    IF(",
              "        OR(ISBLANK([Average # of Facings PW]),ISBLANK([Average # of Facings CW])),",
              "        BLANK(),",
              "        DIVIDE([Average # of Facings CW]-[Average # of Facings PW],[Average # of Facings PW])",
              "    )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0841c77c-f97b-4823-a9fc-2ccdc9182aa5"
          },
          {
            "name": "Average # of Facings vs PY",
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Percentage with 1 decimal place; show to user */",
              "    IF(",
              "        OR(ISBLANK([Average # of Facings PY]),ISBLANK([Average # of Facings CW])),",
              "        BLANK(),",
              "        DIVIDE([Average # of Facings CW]-[Average # of Facings PY],[Average # of Facings PY])",
              "    )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "26a9dd1d-29bb-4482-b3bf-df80f28ad904"
          },
          {
            "name": "Average # of Displays CW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Displays],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "5e42a09d-ab69-4881-8b00-3a4677882aa9"
          },
          {
            "name": "Average # of Displays PW",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Displays],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "fc3dd446-853e-4625-a084-d7b869bc6650"
          },
          {
            "name": "Average # of Displays PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Decimal number with 1 decimal place, hide from user */",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Average # of Displays],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "isHidden": true,
            "lineageTag": "152ddb39-83ff-4456-a1da-bbc780be27f5"
          },
          {
            "name": "Average # of Displays vs PW",
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Percentage with 1 decimal place , show to user*/",
              "    IF(",
              "        OR(ISBLANK([Average # of Displays PW]),ISBLANK([Average # of Displays CW])),",
              "        BLANK(),",
              "        DIVIDE([Average # of Displays CW]-[Average # of Displays PW],[Average # of Displays PW])",
              "    )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c846f9f0-9ceb-4e27-8d85-381bb4ae3b06"
          },
          {
            "name": "Average # of Displays vs PY",
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Percentage with 1 decimal place, show to user */",
              "    IF(",
              "        OR(ISBLANK([Average # of Displays PY]),ISBLANK([Average # of Displays CW])),",
              "        BLANK(),",
              "        DIVIDE([Average # of Displays CW]-[Average # of Displays PY],[Average # of Displays PY])",
              "    )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "adfdede1-7214-4c8f-86b9-6451882f9aff"
          },
          {
            "name": "Availability CW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal point; hide from user */",
              "VAR year_wave_cw = MAX('Calendar'[Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Availability],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "05741b88-9ca5-4a84-b994-4d6954cf6a9a"
          },
          {
            "name": "Availability PW",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal point; hide from user */",
              "VAR year_wave_pw = MAX('Calendar'[Prior Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Availability],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "787da0e8-ebd4-42f1-b350-2a30e06c1bf8"
          },
          {
            "name": "Availability PY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": [
              "",
              "/* Percentage with 1 decimal point; hide from user */ ",
              "VAR year_wave_py = MAX('Calendar'[Prior Year Wave])",
              "VAR results = ",
              "    CALCULATE(",
              "        [Availability],",
              "        REMOVEFILTERS('Calendar'),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    )",
              "//return the results",
              "RETURN results"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "isHidden": true,
            "lineageTag": "09bb76e0-2a1a-41cd-b1dd-5dda1127c4ca"
          },
          {
            "name": "Availability vs PW",
            "displayFolder": "Change vs PW",
            "expression": [
              "",
              "/* Decimal number with 2 decimal points; show to user */",
              "    IF(",
              "        OR(ISBLANK([Availability PW]),ISBLANK([Availability CW])),",
              "        BLANK(),",
              "        ([Availability CW]-[Availability PW])*100",
              "    )"
            ],
            "formatString": "0.00",
            "lineageTag": "4d6bb9ab-013d-4e88-8b88-3118f41d286d"
          },
          {
            "name": "Availability vs PY",
            "displayFolder": "Change vs PY",
            "expression": [
              "",
              "/* Decimal number with 2 decimal points; show to user */",
              "    IF(",
              "        OR(ISBLANK([Availability PY]),ISBLANK([Availability CW])),",
              "        BLANK(),",
              "        ([Availability CW]-[Availability PY])*100",
              "    )",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "a1d5ed66-df2f-4859-87eb-dab6b8d85a6c"
          },
          {
            "name": "wave ending test",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": "max('Calendar'[wave_ending_date]) <= NOW()",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "5c78a179-5fce-4fcb-be01-1d3d7fa1f3f4"
          },
          {
            "name": "User",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": "USERPRINCIPALNAME()",
            "isHidden": true,
            "lineageTag": "b8d3b9ec-0c73-4c4d-a11d-8b97dfae3cec"
          },
          {
            "name": "SOVI Test",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Actual",
            "expression": [
              "/*",
              "The SOVI measure calculates the share of visual inventory.  The user must select/filter using the Product Hierarchy for the formula to work.  The numerator (1st variable) will always be the total facings for the selected/filtered product(s).  The denominator changes depending on the filters from the user.  It will be total facings for All Beverages if the user has selected/filtered against System Brands or Manufacturer (2nd variable).  The denominator will be total facings for all related categories if the user has selected/fitlered against a Trademark or Brand (3rd variable).  ",
              "",
              "SOVI must be filtered by at least one field in the Product Hierarchy. If you filter by System Brands or Manufacturer, SOVI is calculated against all beverage categories. If you filter by Trademark or Brand, SOVI is calculated against only the categories that the products fall under.",
              "*/",
              "",
              "//If it is being used, pre-load variables for CBR Share and ELT Share.   ",
              "VAR Total_Facings = [Total # of Facings]",
              "",
              "VAR ELT_Category_Total_Facings =",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        VALUES ( 'Product'[ko_elt_category] ),",
              "        ALL (",
              "            'Product'[ko_system_brands],",
              "            'Product'[ko_key_manufacturer],",
              "            'Product'[ko_key_trademark],",
              "            'Product'[ko_key_brand]",
              "        )",
              "    )",
              "VAR CBR_Category_Total_Facings =",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        VALUES ( 'Product'[CBR Category]),",
              "        ALL (",
              "            'Product'[ko_system_brands],",
              "            'Product'[ko_key_manufacturer],",
              "            'Product'[ko_key_trademark],",
              "            'Product'[ko_key_brand]",
              "        )",
              "    )",
              "VAR Total_Beverage_Facings =",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        ALL ( 'Product'[ko_system_brands], 'Product'[ko_key_manufacturer] )",
              "    )",
              "",
              "VAR Total_Beverage_Share =",
              "    DIVIDE ( Total_Facings, Total_Beverage_Facings )",
              "    ",
              "VAR ELT_Category_Share =",
              "    DIVIDE ( Total_Facings, ELT_Category_Total_Facings )",
              "    ",
              "VAR CBR_Category_Share =",
              "    DIVIDE ( Total_Facings, CBR_Category_Total_Facings )",
              "    ",
              "//Check for which Category is being filtered.",
              "VAR cat_results = ",
              "IF(",
              "    ISFILTERED('Product'[ko_elt_category]),",
              "    ELT_Category_Share,",
              "        CBR_Category_Share)",
              "    ",
              "VAR Results =",
              "    SWITCH (TRUE(),",
              "    ISFILTERED('Product'[ko_key_brand]), cat_results, ",
              "    ISFILTERED('Product'[ko_key_trademark]), cat_results,",
              "    ISFILTERED('Product'[ko_key_manufacturer]), Total_Beverage_Share,",
              "    ISFILTERED('Product'[ko_system_brands]), Total_Beverage_Share, 1",
              "    )",
              "RETURN",
              "    Results",
              ""
            ],
            "formatString": "0.0000%;-0.0000%;0.0000%",
            "isHidden": true,
            "lineageTag": "70634a33-471a-40a5-a915-1ff47647859c"
          },
          {
            "name": "slicer test",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden Measures",
            "expression": "IF([wave ending test],TRUE(),0)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "8b74ccad-c349-4e96-8969-8e2663ec1261"
          },
          {
            "name": "Average # of Coolers CW",
            "displayFolder": "Hidden Measures",
            "expression": [
              "/* decimal, 2 decimal points, hide from user */",
              "VAR year_wave_cw =",
              "    MAX ( 'Calendar'[Year Wave] )",
              "VAR results =",
              "    CALCULATE (",
              "        [Average # of Coolers],",
              "        REMOVEFILTERS ( 'Calendar' ),",
              "        'Calendar'[Year Wave] = year_wave_cw",
              "    ) //return the results",
              "RETURN",
              "    results"
            ],
            "formatString": "#,##0.00",
            "isHidden": true,
            "lineageTag": "de8fb185-6a4f-4761-a0af-116dfa611274"
          },
          {
            "name": "Average # of Coolers PW",
            "displayFolder": "Hidden Measures",
            "expression": [
              "/* decimal, 2 decimal points, hide from user */",
              "VAR year_wave_pw =",
              "    MAX ( 'Calendar'[Prior Wave] )",
              "VAR results =",
              "    CALCULATE (",
              "        [Average # of Coolers],",
              "        REMOVEFILTERS ( 'Calendar' ),",
              "        'Calendar'[Year Wave] = year_wave_pw",
              "    ) //return the results",
              "RETURN",
              "    results"
            ],
            "formatString": "#,##0.00",
            "isHidden": true,
            "lineageTag": "8c42c6b2-b8c0-44fd-bd9b-4e8498aef2ac"
          },
          {
            "name": "Average # of Coolers PY",
            "displayFolder": "Hidden Measures",
            "expression": [
              "/* Decimal number with 2 decimal place, hide from user */",
              "VAR year_wave_py =",
              "    MAX ( 'Calendar'[Prior Year Wave] )",
              "VAR results =",
              "    CALCULATE (",
              "        [Average # of Coolers],",
              "        REMOVEFILTERS ( 'Calendar' ),",
              "        'Calendar'[Year Wave] = year_wave_py",
              "    ) //return the results",
              "RETURN",
              "    results"
            ],
            "formatString": "#,##0.00",
            "isHidden": true,
            "lineageTag": "8f7d0483-2ba5-499c-85d7-8a66fe4b175e"
          },
          {
            "name": "Average # of Coolers vs PW ",
            "displayFolder": "Change vs PW",
            "expression": [
              "/* percentage, 1 decimal point, show to user */",
              "IF (",
              "    OR (",
              "        ISBLANK ( [Average # of Coolers PW] ),",
              "        ISBLANK ( [Average # of Coolers CW] )",
              "    ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Average # of Coolers CW] - [Average # of Coolers PW],",
              "        [Average # of Coolers PW]",
              "    )",
              ")"
            ],
            "formatString": "#,##0.0",
            "lineageTag": "b7977379-bc3e-4f15-ab05-2c838ebbc623"
          },
          {
            "name": "Average # of Coolers vs PY",
            "displayFolder": "Change vs PY",
            "expression": [
              "/* Percentage with 1 decimal place, show to user */",
              "IF (",
              "    OR (",
              "        ISBLANK ( [Average # of Coolers PY] ),",
              "        ISBLANK ( [Average # of Coolers CW] )",
              "    ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Average # of Coolers CW] - [Average # of Coolers PY],",
              "        [Average # of Coolers PY]",
              "    )",
              ")"
            ],
            "formatString": "#,##0.0",
            "lineageTag": "b594792b-0588-43ac-ae41-3cdd0b1f2fc8"
          },
          {
            "name": "Category_Total_Facings",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        VALUES ( 'Product'[ko_elt_category] ),",
              "        ALL (",
              "            'Product'[ko_system_brands],",
              "            'Product'[ko_key_manufacturer],",
              "            'Product'[ko_key_trademark],",
              "            'Product'[ko_key_brand]))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8b233f4c-9368-4a79-92d3-d8b81226c0e4"
          },
          {
            "name": "Total_Beverage_Facings",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "    CALCULATE (",
              "        [Total # of Facings],",
              "        ALL ( 'Product'[ko_system_brands], 'Product'[ko_key_manufacturer] ))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d364751-fd9d-407e-9f8c-7de95e93d07e"
          },
          {
            "name": "Sovi test variance",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[SOVI] - [SOVI Test]",
            "formatString": "0.00000",
            "isHidden": true,
            "lineageTag": "19affc84-7f13-49ef-82f1-1326606ab788"
          }
        ],
        "partitions": [
          {
            "name": "iRED Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, DataBase),",
                "    ired_mdl_vw_fact_facing = Source{[Schema=\"ired_mdl\",Item=\"vw_fact_facing\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(ired_mdl_vw_fact_facing,{{\"visitdate\", \"Visit Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Store Area",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sub_Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c3135496-6eb2-45c6-bedf-b606ee0b0c90",
            "sourceColumn": "Sub_Location",
            "summarizeBy": "none"
          },
          {
            "name": "Sub_Location_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "4c0da0f1-33b8-4f69-b0c5-8a366f4c1383",
            "sourceColumn": "Sub_Location_Code",
            "summarizeBy": "none"
          },
          {
            "name": "location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9079075e-494e-4237-a6a5-b7d328711bb8",
            "sourceColumn": "location",
            "summarizeBy": "none"
          }
        ],
        "description": "ired_mdl vw_Dim_Location",
        "hierarchies": [
          {
            "name": "Location Hierarchy",
            "levels": [
              {
                "name": "Location",
                "column": "location",
                "lineageTag": "a3f4afd2-fa3a-40fe-9c25-8d69b5c72054",
                "ordinal": 0
              },
              {
                "name": "Sub Location",
                "column": "Sub_Location",
                "lineageTag": "ca8e25b3-4578-4995-af80-241b91c24437",
                "ordinal": 1
              }
            ],
            "lineageTag": "891b6ef4-afa2-42c0-8fd1-776ea09dfc41"
          }
        ],
        "lineageTag": "1c20b17b-fe51-4196-a65e-a33269f11903",
        "partitions": [
          {
            "name": "Store Area",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, DataBase),",
                "    ired_mdl_vw_dim_location = Source{[Schema=\"ired_mdl\",Item=\"vw_dim_location\"]}[Data]",
                "in",
                "    ired_mdl_vw_dim_location"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f23344b-d075-4517-bf06-164670c2b0e8",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1e2ae400-82a6-466a-9850-2f59ec64fbca",
            "sourceColumn": "Wave",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12375a23-3012-4584-b296-b8951e0da619",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8d10193d-c503-4eea-9fb7-8dbabdf4960f",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week Ending Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "de04e0b5-a226-4c13-9f69-0c76fbaf57f8",
            "sourceColumn": "Fiscal Week Ending Date",
            "summarizeBy": "none"
          },
          {
            "name": "wave_ending_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "m/d/yyyy",
            "isHidden": true,
            "lineageTag": "6de4528d-1901-4ba1-9033-dd74123e8176",
            "sourceColumn": "wave_ending_date",
            "summarizeBy": "none"
          },
          {
            "name": "Year Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7969f7ff-964c-457b-8105-5908c18946c6",
            "sourceColumn": "Year Wave",
            "summarizeBy": "none"
          },
          {
            "name": "year_wave_sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e720cf9a-c2ac-48ca-93a0-469125fb5303",
            "sourceColumn": "year_wave_sort",
            "summarizeBy": "none"
          },
          {
            "name": "Vist Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "798532f1-a73e-4322-a0e6-be53462194b3",
            "sourceColumn": "Vist Date",
            "summarizeBy": "none"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8e9ddae8-20f0-499f-84dd-7603a8cd1196",
            "sourceColumn": "month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month Ending",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "7df68c08-42d2-42dc-9306-7e5d6c7025f7",
            "sourceColumn": "Fiscal Month Ending",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e63ab5fe-beab-44b1-b957-1755ad867fe8",
            "sourceColumn": "Prior Wave",
            "summarizeBy": "none"
          },
          {
            "name": "Prior Year Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f0b1b7b7-28ef-4ecb-bcc0-ccb75da113e8",
            "sourceColumn": "Prior Year Wave",
            "summarizeBy": "none"
          },
          {
            "name": "Completed Wave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "IF('Calendar'[wave_ending_date] <= NOW(),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "97666e0e-23c3-4ca3-93a5-953628732dd0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Wave Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "58769770-a288-42c0-bd42-207325fae768",
                "ordinal": 0
              },
              {
                "name": "Wave",
                "column": "Wave",
                "lineageTag": "02587dd9-c2dc-487b-92ad-7a310798e39c",
                "ordinal": 1
              }
            ],
            "lineageTag": "2c6c3adb-7f92-485e-b588-9bc01ad7764d"
          }
        ],
        "lineageTag": "5ff03b22-3162-4326-b6f2-42b10594a5e4",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"syn-tccc-udp-dnao-us2-prd-01-ondemand.sql.azuresynapse.net\"),",
                "    DnAIQDb_PreProd = Source{[Name=\"DnAIQDb_PreProd\"]}[Data],",
                "    ired_mdl_vw_dim_calendar = DnAIQDb_PreProd{[Schema=\"ired_mdl\",Item=\"vw_dim_calendar\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(ired_mdl_vw_dim_calendar,{{\"month_ending_date\", \"Fiscal Month Ending\"}, {\"prior_wave\", \"Prior Wave\"}, {\"prior_year_wave\", \"Prior Year Wave\"}, {\"quarter\", \"Fiscal Quarter\"}, {\"visitdate\", \"Vist Date\"}, {\"wave\", \"Wave\"}, {\"week_of_month\", \"Fiscal Week\"}, {\"week_ending_date\", \"Fiscal Week Ending Date\"}, {\"year\", \"Year\"}, {\"year_wave\", \"Year Wave\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Outlet",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "bottler_ownership_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61853430-81d8-480c-8e75-daf68c158522",
            "sourceColumn": "bottler_ownership_id",
            "summarizeBy": "none"
          },
          {
            "name": "bottler_delivery_point_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6c74c727-91bb-45b6-89cc-42a984f0da3e",
            "sourceColumn": "bottler_delivery_point_number",
            "summarizeBy": "none"
          },
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2c203d9b-885e-4c9a-937f-0a5d5908e91a",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "outlet_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "d90d7b6c-4c55-412f-9791-394b4d29be81",
            "sourceColumn": "outlet_key",
            "summarizeBy": "none"
          },
          {
            "name": "Bottler",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "369ea12c-17c6-44a6-86a7-e0eb112f1795",
            "sourceColumn": "Bottler",
            "summarizeBy": "none"
          },
          {
            "name": "Bottler MU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "bottler market unit",
            "isHidden": true,
            "lineageTag": "22d80cb8-8c3b-421e-80d7-47e7afbb2f97",
            "sourceColumn": "Bottler MU",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Center",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c9a35f62-1e52-434d-b446-4cf3ad1a98cc",
            "sourceColumn": "Sales Center",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "cbs_customer_name",
            "isHidden": true,
            "lineageTag": "b7ea8dbe-5746-48bd-82b6-b64e83037d26",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Banner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "cbs_subsidiary_name",
            "isHidden": true,
            "lineageTag": "4bc697d2-4123-4c38-beff-fc10d2794a7c",
            "sourceColumn": "Customer Banner",
            "summarizeBy": "none"
          },
          {
            "name": "Bottler Tier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "description": "groups bottler in tiers: tier 1 includes top 10 bottlers and Tier 2 includes the remaining bottlers available in iRED data",
            "isHidden": true,
            "lineageTag": "41461910-2ea3-453f-ab69-61405c2353b2",
            "sourceColumn": "Bottler Tier",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "levels": [
              {
                "name": "Customer Banner",
                "column": "Customer Banner",
                "lineageTag": "a89fe65d-b8a0-47a4-93d7-6e52b83e79d5",
                "ordinal": 2
              },
              {
                "name": "Channel",
                "column": "Channel",
                "lineageTag": "707e93ca-83cc-4eca-8b24-0c37ddd6653c",
                "ordinal": 0
              },
              {
                "name": "Customer",
                "column": "Customer",
                "lineageTag": "ddbb57cc-d708-435e-9494-16dfc3ddd0ad",
                "ordinal": 1
              }
            ],
            "lineageTag": "a68554f4-6ed4-4921-b01b-a1000e605766"
          },
          {
            "name": "Bottler Hierarchy",
            "levels": [
              {
                "name": "Bottler Tier",
                "column": "Bottler Tier",
                "lineageTag": "c2ad244b-6e13-491a-b737-018e472e360e",
                "ordinal": 0
              },
              {
                "name": "Bottler",
                "column": "Bottler",
                "lineageTag": "f4d6fc03-2b82-4503-a205-3ee78e0d9111",
                "ordinal": 1
              },
              {
                "name": "Bottler MU",
                "column": "Bottler MU",
                "lineageTag": "750e4a13-6827-4e0e-8d6b-bd6aa48d9818",
                "ordinal": 2
              },
              {
                "name": "Sales Center",
                "column": "Sales Center",
                "lineageTag": "129962ab-c815-40b1-9f6b-01317784ea7e",
                "ordinal": 3
              }
            ],
            "lineageTag": "425ecc29-2461-44da-8b9d-fd6bae9f7aca"
          }
        ],
        "lineageTag": "3fb4fd70-6a95-4d6c-aa6f-87f231ef8026",
        "partitions": [
          {
            "name": "Outlet",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Server, DataBase),",
                "    ired_mdl_vw_dim_outlet = Source{[Schema=\"ired_mdl\",Item=\"vw_dim_outlet\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(ired_mdl_vw_dim_outlet,{{\"bottler\", \"Bottler\"}, {\"bottler_market_unit\", \"Bottler MU\"}, {\"bottler_sales_branch\", \"Sales Center\"}, {\"channel\", \"Channel\"}, {\"cbs_customer_name\", \"Customer\"}, {\"cbs_subsidiary_name\", \"Customer Banner\"}}),",
                "  #\"Renamed Columns 1\" = Table.RenameColumns(#\"Renamed Columns\", {{\"bottler_tier\", \"Bottler Tier\"}})",
                "in",
                "    #\"Renamed Columns 1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}