table Calendar
	lineageTag: 125a55a7-f38d-48af-9576-3434a2be4778
	dataCategory: Time

	column dim_date_key
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 6695e402-084a-4b41-ae77-d2e216d55d7d
		summarizeBy: none
		sourceColumn: dim_date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: ab5338b4-2d57-49b5-85dc-a512906ee956
		summarizeBy: sum
		sourceColumn: date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Calendar Date'
		dataType: dateTime
		isHidden
		isKey
		formatString: Short Date
		displayFolder: Hidden
		lineageTag: 586be44e-7cac-44c0-9408-96b8862cec23
		summarizeBy: none
		sourceColumn: Calendar Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: cb47a8a8-a434-4856-8050-b46c9f32b49d
		summarizeBy: none
		sourceColumn: Fiscal Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 29f8713d-fee5-4a33-ab7e-153671f89db2
		summarizeBy: none
		sourceColumn: quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: a1695e9b-19cb-44fd-b889-e074aa186d31
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_sort_number

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column fiscal_week
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 2e589bd4-301f-4fd8-968a-c124601fc511
		summarizeBy: none
		sourceColumn: fiscal_week

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = User

	column fiscal_year_quarter
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 7a172323-ac6a-419e-9b11-019f5e4db866
		summarizeBy: none
		sourceColumn: fiscal_year_quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year_month_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 1f43ccb6-0273-48fe-aeb1-57df3ccb8d32
		summarizeBy: sum
		sourceColumn: year_month_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fiscal_year_month_week
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 7eccb8ef-aa98-4af8-acf5-b3d1f62f2910
		summarizeBy: sum
		sourceColumn: fiscal_year_month_week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Ending Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54e3e70e-3312-4607-b493-3bdee22eafc7
		summarizeBy: none
		sourceColumn: Fiscal Quarter Ending Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Month Ending Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9430ff33-2593-4fb3-9b8f-ffc9aa7f2705
		summarizeBy: none
		sourceColumn: Fiscal Month Ending Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Week Ending Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a1a9a8a8-6113-4be1-95b1-16da2e785e11
		summarizeBy: none
		sourceColumn: Fiscal Week Ending Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column quarter_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 01cf897f-f44e-4f39-b6e9-ae15f42dcffc
		summarizeBy: sum
		sourceColumn: quarter_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column month_sort_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 6b5fb9ce-323e-478d-bf0f-c79357217cb3
		summarizeBy: sum
		sourceColumn: month_sort_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week Number'
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 83c1576b-3dfd-4fbd-9a2b-308acca7feea
		summarizeBy: none
		sourceColumn: Week Number
		sortByColumn: fiscal_week

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sequential Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 7462331e-2f75-4d17-bdd5-e90bf061c74c
		summarizeBy: sum
		sourceColumn: Sequential Quarter Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sequential Month Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: d5ecd6c6-5852-43d4-86fe-7974da9aeb01
		summarizeBy: sum
		sourceColumn: Sequential Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sequential Week Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: 2a55e5ed-b814-46d8-95d2-87ef2275a2c2
		summarizeBy: sum
		sourceColumn: Sequential Week Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sequential_day_number
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: eb21a38f-7930-487f-abf5-cf0165839109
		summarizeBy: sum
		sourceColumn: sequential_day_number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week in Quarter Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: e7894bc0-16f0-4337-9925-a3abcd8f66a6
		summarizeBy: sum
		sourceColumn: Fiscal Week in Quarter Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Week in Month Number'
		dataType: int64
		isHidden
		formatString: 0
		displayFolder: Hidden
		lineageTag: f97f1177-b517-4fdb-8757-8d0129cd4ed4
		summarizeBy: sum
		sourceColumn: Fiscal Week in Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sovi_wave
		dataType: double
		isHidden
		displayFolder: Hidden
		lineageTag: f487d341-492d-4a57-ad1a-9fe3345c40fb
		summarizeBy: sum
		sourceColumn: sovi_wave

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sovi_wave_year
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 8c7d59df-c79a-47a9-8ccd-bb6a0d5b4eeb
		summarizeBy: none
		sourceColumn: sovi_wave_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sovi_prior_wave
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 16a86385-ca1a-4a4e-b041-90f9f875b2a1
		summarizeBy: none
		sourceColumn: sovi_prior_wave

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sovi_wave_prior_year
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: 0921d511-6106-469a-aa2b-437118b984a8
		summarizeBy: none
		sourceColumn: sovi_wave_prior_year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sovi_wave_ending_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		displayFolder: Hidden
		lineageTag: a3583fe1-0e28-4239-b391-a1d499cba707
		summarizeBy: none
		sourceColumn: sovi_wave_ending_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year_wave_sort
		dataType: string
		isHidden
		displayFolder: Hidden
		lineageTag: bf8b745e-4a59-4a1c-8311-d10f2c5b3dd8
		summarizeBy: none
		sourceColumn: year_wave_sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Year Hierarchy'
		lineageTag: 8759cfc1-c73e-436b-b27f-48e187e1a76c

		level 'Fiscal Year'
			lineageTag: 209b0c7a-7128-4dcc-b807-ee6e16eac8f6
			column: 'Fiscal Year'

		level 'Fiscal Quarter'
			lineageTag: 4b60f78e-1091-413f-9873-f3e00cc7c958
			column: quarter

		level 'Fiscal Month'
			lineageTag: 05b678ee-f555-465c-a66c-c0dc553845ef
			column: month

		level 'Fiscal Week'
			lineageTag: 930ce919-0e2f-4735-b090-d39f2b7444f4
			column: 'Week Number'

	partition Calendar = m
		mode: import
		source =
				let
				    Source = Sql.Database(Server, Database,[CommandTimeout=#duration(0,0,180,0)]),
				    invoice_mdl_vw_Dim_Calendar = Source{[Schema="dbo",Item="vw_Dim_Calendar"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(invoice_mdl_vw_Dim_Calendar,{"dim_date_key", "ymdid", "date", "fiscal_year", "fiscal_quarter", "fiscal_month", "fiscal_week", "fiscal_year_quarter", "fiscal_year_month", "fiscal_year_month_week", "fiscal_quarter_ending_date", "fiscal_month_ending_date", "fiscal_week_ending_date", "quarter_number", "month_number", "week_number", "sequential_quarter_number", "sequential_month_number", "sequential_week_number", "sequential_day_number", "fiscal_week_in_quarter_number", "fiscal_week_in_month_number", "sovi_wave", "sovi_wave_year", "sovi_prior_wave", "sovi_wave_prior_year", "sovi_wave_ending_date", "year_wave_sort"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"fiscal_month_ending_date", "Fiscal Month Ending Date"}, {"fiscal_week_ending_date", "Fiscal Week Ending Date"}, {"date", "Calendar Date"}, {"ymdid", "date_key"}, {"fiscal_year", "year"}, {"fiscal_quarter", "quarter"}, {"fiscal_month", "month"}, {"month_number", "month_sort_number"}, {"fiscal_year_month", "year_month_number"}, {"week_number", "Week Number"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Calendar Date", type date}, {"Fiscal Month Ending Date", type date}, {"fiscal_quarter_ending_date", type date}, {"sovi_wave_ending_date", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Calendar Date] >= Date.AddYears(Date.From(DateTime.LocalNow()),-3) and [Calendar Date]  <= Date.From(DateTime.LocalNow())),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each true),
				    #"Renamed Columns1" = Table.RenameColumns(#"Filtered Rows1",{{"fiscal_quarter_ending_date", "Fiscal Quarter Ending Date"}, {"year", "Fiscal Year"}, {"sequential_quarter_number", "Sequential Quarter Number"}, {"sequential_month_number", "Sequential Month Number"}, {"sequential_week_number", "Sequential Week Number"}, {"fiscal_week_in_quarter_number", "Fiscal Week in Quarter Number"}, {"fiscal_week_in_month_number", "Fiscal Week in Month Number"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

